return {
	[1] = "Elites spawn more often.",
	[2] = "Normal enemies are deadlier.",
	[3] = "Elites are deadlier.",
	[4] = "Bosses are deadlier.",
	[5] = "Heal less after Boss battles.",
	[6] = "Start each run damaged.",
	[7] = "Normal enemies are tougher.",
	[8] = "Elites are tougher.",
	[9] = "Bosses are tougher.",
	[10] = "Start each run cursed.",
	[11] = "Fewer Potion Slots.",
	[12] = "Upgraded cards appear less often.",
	[13] = "Poor bosses.",
	[14] = "Lower Max HP.",
	[15] = "Unfavorable Events.",
	[16] = "Shops are more costly.",
	[17] = "Normal enemies have more challenging movesets and abilities.",
	[18] = "Elites have more challenging movesets and abilities.",
	[19] = "Bosses have more challenging movesets and abilities.",
	[20] = "(Max Level) Double boss.",
}