local all_data = {
  ["nodata_fallback"] = {
    Cost = 0,
    Color = "Colorless",
    Traits = { NoList = true },
    Image = "Site-Logo.png",
    Type = "Skill",
    Rarity = "Basic",
    Text = "Card \"BADCARD\"not found in [[Module:Cards/Data]]."
  },
  ["Bash"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Bash.png",
    Type = "Attack",
    Rarity = "Basic",
    Text = "Deal [8|10] damage.<br>Apply [2|3] $Vulnerable."
  },
  ["Defend (Ironclad)"] = {
    Cost = 1,
    ID = "Defend (Ironclad)",
    Color = "Red",
    Image = "Red-Defend.png",
    Rarity = "Basic",
    Text = "Gain [5|8] $Block.",
    Type = "Skill",
    Link = "Defend (Ironclad)",
  },
  ["Strike (Ironclad)"] = {
    Cost = 1,
    ID = "Strike (Ironclad)",
    Color = "Red",
    Image = "Red-Strike.png",
    Rarity = "Basic",
    Text = "Deal [6|9] damage.",
    Type = "Attack",
    Link = "Strike (Ironclad)",
  },
  ["Anger"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Anger.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [6|8] damage.<br>Add a copy of this card into your discard pile.",
  },
  ["Armaments"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Armaments.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain 5 $Block.<br>$Upgrade [a card|all cards] in your hand for the rest of combat.",
  },
  ["Body Slam"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-BodySlam.png",
    CostPlus = 0,
    Text = "Deal damage equal to your $Block.",
    Type = "Attack",
    Rarity = "Common",
  },
  ["Clash"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Clash.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Can only be played if every card in your hand is an Attack.<br>Deal [14|18] damage.",
  },
  ["Cleave"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Cleave.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [8|11] damage to ALL enemies.",
  },
  ["Clothesline"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Clothesline.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [12|14] damage.<br>Apply [2|3] $Weak.",
  },
  ["Flex"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Flex.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [2|4] $Strength.<br>At the end of this turn, lose [2|4] $Strength.",
  },
  ["Havoc"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Havoc.png",
    CostPlus = 0,
    Text = "Play the top card of your draw pile and $Exhaust it.",
    Type = "Skill",
    Rarity = "Common",
  },
  ["Headbutt"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Headbutt.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [9|12] damage.<br>Put a card from your discard pile on top of your draw pile.",
  },
  ["Heavy Blade"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-HeavyBlade.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal 14 damage.<br>$Strength affects this card [3|5] times.",
  },
  ["Iron Wave"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-IronWave.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Gain [5|7] $Block.<br>Deal [5|7] damage.",
  },
  ["Perfected Strike"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-PerfectedStrike.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal 6 damage.<br>Deals [2|3] additional damage for ALL your cards containing \"Strike\".",
  },
  ["Pommel Strike"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-PommelStrike.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [9|10] damage.<br>Draw [1|2] [card|cards].",
  },
  ["Shrug It Off"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-ShrugItOff.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [8|11] $Block.<br>Draw 1 card.",
  },
  ["Sword Boomerang"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-SwordBoomerang.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal 3 damage to a random enemy [3|4] times.",
  },
  ["Thunderclap"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Thunderclap.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [4|7] damage and apply 1 $Vulnerable to ALL enemies.",
  },
  ["True Grit"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-TrueGrit.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [7|9] $Block.<br>$Exhaust 1 card[ at random|].",
  },
  ["Twin Strike"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-TwinStrike.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [5|7] damage twice.",
  },
  ["Warcry"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Warcry.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Draw [1|2] [card|cards].<br>Put a card from your hand onto the top of your draw pile.<br>$Exhaust.",
  },
  ["Wild Strike"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-WildStrike.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [12|17] damage.<br>Shuffle a {{C|Wound}} into your draw pile.",
  },
  ["Battle Trance"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-BattleTrance.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Draw [3|4] cards.<br>You cannot draw additional cards this turn.",
  },
  ["Blood for Blood"] = {
    Cost = 4,
    Color = "Red",
    Image = "Red-BloodforBlood.png",
    CostPlus = 3,
    Text = "Costs 1 less @RE<br>for each time you lose HP this combat.<br>Deal [18|22] damage.",
    Type = "Attack",
    Rarity = "Uncommon",
  },
  ["Bloodletting"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Bloodletting.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Lose 3 HP.<br>Gain [@RE @RE|@RE @RE @RE].",
  },
  ["Burning Pact"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-BurningPact.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Exhaust 1 card.<br>Draw [2|3] cards.",
  },
  ["Carnage"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Carnage.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "$Ethereal.<br>Deal [20|28] damage.",
  },
  ["Combust"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Combust.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the end of your turn, lose 1 HP and deal [5|7] damage to ALL enemies.",
  },
  ["Dark Embrace"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-DarkEmbrace.png",
    CostPlus = 1,
    Text = "Whenever a card is $Exhausted,<br>draw 1 card.",
    Type = "Power",
    Rarity = "Uncommon",
  },
  ["Disarm"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Disarm.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Enemy loses [2|3] $Strength.<br>$Exhaust.",
  },
  ["Dropkick"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Dropkick.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [5|8] damage.<br>If the enemy has $Vulnerable, gain @RE and draw 1 card.",
  },
  ["Dual Wield"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-DualWield.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Choose an Attack or Power card. Add [a copy|2 copies] of that card into your hand.",
  },
  ["Entrench"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Entrench.png",
    CostPlus = 1,
    Text = "Double your $Block.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Evolve"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Evolve.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you draw a {{QueryLink|Cards|type:Status|Status}} card, draw [1|2] [card|cards].",
  },
  ["Feel No Pain"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-FeelNoPain.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever a card is $Exhausted,<br>gain [3|4] $Block.",
  },
  ["Fire Breathing"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-FireBreathing.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you draw a {{QueryLink|Cards|type:Status|Status}} or {{QueryLink|Cards|type:Curse|Curse}} card, deal [6|10] damage to ALL enemies.",
  },
  ["Flame Barrier"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-FlameBarrier.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [12|16] $Block.<br>Whenever you are attacked this turn, deal [4|6] damage back.",
  },
  ["Ghostly Armor"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-GhostlyArmor.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Ethereal.<br>Gain [10|13] $Block.",
  },
  ["Hemokinesis"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Hemokinesis.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Lose 2 HP.<br>Deal [15|20] damage.",
  },
  ["Infernal Blade"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-InfernalBlade.png",
    CostPlus = 0,
    Text = "Add a random Attack into your hand.<br>It costs 0 this turn.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Inflame"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Inflame.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Gain [2|3] $Strength.",
  },
  ["Intimidate"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Intimidate.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply [1|2] $Weak to ALL enemies.<br>$Exhaust.",
  },
  ["Metallicize"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Metallicize.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the end of your turn, gain [3|4] $Block.",
  },
  ["Power Through"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-PowerThrough.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Add 2 {{C|Wound|Wounds}} into your hand.<br>Gain [15|20] $Block.",
  },
  ["Pummel"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Pummel.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal 2 damage [4|5] times.<br>$Exhaust.",
  },
  ["Rage"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Rage.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Whenever you play an Attack this turn, gain [3|5] $Block.",
  },
  ["Rampage"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Rampage.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal 8 damage.<br>Increase this card's damage by [5|8] this combat.",
  },
  ["Reckless Charge"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-RecklessCharge.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [7|10] damage.<br>Shuffle a {{C|Dazed}} into your draw pile.",
  },
  ["Rupture"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Rupture.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you lose HP from a card,<br>gain [1|2] $Strength.",
  },
  ["Searing Blow"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-SearingBlow.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [12|16] damage.<br>Can be $Upgraded any number of times.",
  },
  ["Second Wind"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-SecondWind.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Exhaust all non-Attack cards in your hand. Gain [5|7] $Block for each card $Exhausted.",
  },
  ["Seeing Red"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-SeeingRed.png",
    CostPlus = 0,
    Text = "Gain @RE @RE.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Sentinel"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Sentinel.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [5|8] $Block.<br>If this card is $Exhausted,<br>gain [@RE@RE|@RE@RE@RE].",
  },
  ["Sever Soul"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-SeverSoul.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "$Exhaust all non-Attack cards in your hand.<br>Deal [16|22] damage.",
  },
  ["Shockwave"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Shockwave.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply [3|5] $Weak and $Vulnerable to ALL enemies.<br>$Exhaust.",
  },
  ["Spot Weakness"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-SpotWeakness.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "If the enemy intends to attack, gain [3|4] $Strength.",
  },
  ["Uppercut"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Uppercut.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal 13 damage.<br>Apply [1|2] $Weak.<br>Apply [1|2] $Vulnerable.",
  },
  ["Whirlwind"] = {
    Text = "Deal [5|8] damage to ALL enemies X times.",
    Color = "Red",
    Image = "Red-Whirlwind.png",
    Cost = -1,
    Type = "Attack",
    Rarity = "Uncommon",
  },
  ["Barricade"] = {
    Cost = 3,
    Color = "Red",
    Image = "Red-Barricade.png",
    CostPlus = 2,
    Text = "$Block is not removed at the start of your turn.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Berserk"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Berserk.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Gain [2|1] $Vulnerable.<br>At the start of your turn, gain @RE.",
  },
  ["Bludgeon"] = {
    Cost = 3,
    Color = "Red",
    Image = "Red-Bludgeon.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [32|42] damage.",
  },
  ["Brutality"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Brutality.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "[|$Innate.<br>]At the start of your turn, lose 1 HP and draw 1 card.",
  },
  ["Corruption"] = {
    Cost = 3,
    Color = "Red",
    Image = "Red-Corruption.png",
    CostPlus = 2,
    Text = "Skills cost 0.<br>Whenever you play a Skill, $Exhaust it.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Demon Form"] = {
    Cost = 3,
    Color = "Red",
    Image = "Red-DemonForm.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "At the start of your turn, gain [2|3] $Strength.",
  },
  ["Double Tap"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-DoubleTap.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "This turn, your next [Attack is|2 Attacks are] played twice.",
  },
  ["Exhume"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Exhume.png",
    CostPlus = 0,
    Text = "Put a card from your $Exhaust pile into your hand.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Feed"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-Feed.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [10|12] damage.<br>If $Fatal, raise your Max HP by [3|4]. $Exhaust.",
  },
  ["Fiend Fire"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-FiendFire.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "$Exhaust your hand.<br>Deal [7|10] damage for each card $Exhausted.<br>$Exhaust.",
  },
  ["Immolate"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Immolate.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [21|28] damage to ALL enemies.<br>Add a {{C|Burn}} into your discard pile.",
  },
  ["Impervious"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Impervious.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Gain [30|40] $Block.<br>$Exhaust.",
  },
  ["Juggernaut"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Juggernaut.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Whenever you gain $Block, deal [5|7] damage to a random enemy.",
  },
  ["Limit Break"] = {
    Cost = 1,
    Color = "Red",
    Image = "Red-LimitBreak.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Double your $Strength.[<br>$Exhaust.|]",
  },
  ["Offering"] = {
    Cost = 0,
    Color = "Red",
    Image = "Red-Offering.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Lose 6 HP.<br>Gain @RE @RE.<br>Draw [3|5] cards.<br>$Exhaust.",
  },
  ["Reaper"] = {
    Cost = 2,
    Color = "Red",
    Image = "Red-Reaper.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [4|5] damage to ALL enemies. Heal HP equal to unblocked damage.<br>$Exhaust.",
  },
  ["Defend (Silent)"] = {
    Cost = 1,
    ID = "Defend (Silent)",
    Color = "Green",
    Image = "Green-Defend.png",
    Rarity = "Basic",
    Text = "Gain [5|8] $Block.",
    Type = "Skill",
    Link = "Defend (Silent)",
  },
  ["Strike (Silent)"] = {
    Cost = 1,
    ID = "Strike (Silent)",
    Color = "Green",
    Image = "Green-Strike.png",
    Rarity = "Basic",
    Text = "Deal [6|9] damage.",
    Type = "Attack",
    Link = "Strike (Silent)",
  },
  ["Neutralize"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Neutralize.png",
    Type = "Attack",
    Rarity = "Basic",
    Text = "Deal [3|4] damage.<br>Apply [1|2] $Weak.",
  },
  ["Survivor"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Survivor.png",
    Type = "Skill",
    Rarity = "Basic",
    Text = "Gain [8|11] $Block.<br>Discard 1 card.",
  },
  ["Acrobatics"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Acrobatics.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Draw [3|4] cards.<br>Discard 1 card.",
  },
  ["Backflip"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Backflip.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [5|8] $Block.<br>Draw 2 cards.",
  },
  ["Bane"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Bane.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|10] damage.<br>If the enemy has $Poison, deal [7|10] damage again.",
  },
  ["Blade Dance"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-BladeDance.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Add [3|4] {{C|Shiv|Shivs}} into your hand.",
  },
  ["Cloak and Dagger"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-CloakandDagger.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain 6 $Block.<br>Add [1|2] {{C|Shiv|[Shiv|Shivs]}} into your hand.",
  },
  ["Dagger Spray"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-DaggerSpray.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [4|6] damage to ALL enemies twice.",
  },
  ["Dagger Throw"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-DaggerThrow.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [9|12] damage.<br>Draw 1 card. <br>Discard 1 card.",
  },
  ["Deadly Poison"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-DeadlyPoison.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Apply [5|7] $Poison.",
  },
  ["Deflect"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Deflect.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [4|7] $Block.",
  },
  ["Dodge and Roll"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-DodgeandRoll.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [4|6] $Block.<br>Next turn, gain [4|6] $Block.",
  },
  ["Flying Knee"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-FlyingKnee.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [8|11] damage.<br>Next turn, gain @GE.",
  },
  ["Outmaneuver"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Outmaneuver.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Next turn,<br>gain [@GE @GE|@GE @GE @GE].",
  },
  ["Piercing Wail"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-PiercingWail.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "ALL enemies lose [6|8] $Strength this turn.<br>$Exhaust.",
  },
  ["Poisoned Stab"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-PoisonedStab.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [6|8] damage.<br>Apply [3|4] $Poison.",
  },
  ["Prepared"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Prepared.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Draw [1|2] [card|cards].<br>Discard [1|2] [card|cards].",
  },
  ["Quick Slash"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-QuickSlash.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [8|12] damage.<br>Draw 1 card.",
  },
  ["Slice"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Slice.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [6|9] damage.",
  },
  ["Sneaky Strike"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-SneakyStrike.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [12|16] damage.<br>If you have discarded a card this turn,<br>gain @GE @GE.",
  },
  ["Sucker Punch"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-SuckerPunch.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|9] damage.<br>Apply [1|2] $Weak.",
  },
  ["Accuracy"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Accuracy.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "{{C|Shiv|Shivs}} deal [4|6] additional damage.",
  },
  ["All-Out Attack"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-All-OutAttack.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [10|14] damage to ALL enemies.<br>Discard 1 card at random.",
  },
  ["Backstab"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Backstab.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "$Innate.<br>Deal [11|15] damage.<br>$Exhaust.",
  },
  ["Blur"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Blur.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [5|8] $Block.<br>$Block is not removed at the start of your next turn.",
  },
  ["Bouncing Flask"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-BouncingFlask.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply 3 $Poison to a random enemy [3|4] times.",
  },
  ["Calculated Gamble"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-CalculatedGamble.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Discard your hand,<br>then draw that many cards.[<br>$Exhaust.|]",
  },
  ["Caltrops"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Caltrops.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you are attacked, deal [3|5] damage back.",
  },
  ["Catalyst"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Catalyst.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "[Double|Triple] the enemy's $Poison.<br>$Exhaust.",
  },
  ["Choke"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-Choke.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal 12 damage.<br>Whenever you play a card this turn, the enemy loses [3|5] HP.",
  },
  ["Concentrate"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Concentrate.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Discard [3|2] cards.<br>Gain @GE @GE.",
  },
  ["Crippling Cloud"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-CripplingCloud.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply [4|7] $Poison and 2 $Weak to ALL enemies.<br>$Exhaust.",
  },
  ["Dash"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-Dash.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Gain [10|13] $Block.<br>Deal [10|13] damage.",
  },
  ["Distraction"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Distraction.png",
    CostPlus = 0,
    Text = "Add a random Skill into your hand.<br>It costs 0 this turn.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Endless Agony"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-EndlessAgony.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Whenever you draw this card, add a copy of it into your hand.<br>Deal [4|6] damage.<br>$Exhaust.",
  },
  ["Escape Plan"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-EscapePlan.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Draw 1 card.<br>If you draw a Skill, gain [3|5] $Block.",
  },
  ["Eviscerate"] = {
    Cost = 3,
    Color = "Green",
    Image = "Green-Eviscerate.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Costs 1 less @GE for each card discarded this turn.<br>Deal [7|9] damage 3 times.",
  },
  ["Expertise"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Expertise.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Draw cards until you have [6|7] in your hand.",
  },
  ["Finisher"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Finisher.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [6|8] damage for each Attack played this turn.",
  },
  ["Flechettes"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Flechettes.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [4|6] damage for each Skill in your hand.",
  },
  ["Footwork"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Footwork.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Gain [2|3] $Dexterity.",
  },
  ["Heel Hook"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-HeelHook.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [5|8] damage. <br>If the enemy has $Weak, <br>gain @GE and draw 1 card.",
  },
  ["Infinite Blades"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-InfiniteBlades.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "[|$Innate. ]At the start of your turn, add a {{C|Shiv}} into your hand.",
  },
  ["Leg Sweep"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-LegSweep.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply [2|3] $Weak.<br>Gain [11|14] $Block.",
  },
  ["Masterful Stab"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-MasterfulStab.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Costs 1 additional @GE for each time you lose HP this combat.<br>Deal [12|16] damage.",
  },
  ["Noxious Fumes"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-NoxiousFumes.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the start of your turn, apply [2|3] $Poison to ALL enemies.",
  },
  ["Predator"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-Predator.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [15|20] damage.<br>Next turn, draw 2 additional cards.",
  },
  ["Reflex"] = {
    Cost = -2,
    Color = "Green",
    Image = "Green-Reflex.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Unplayable.<br>If this card is discarded from your hand, draw [2|3] cards.",
  },
  ["Riddle with Holes"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-RiddlewithHoles.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [3|4] damage 5 times.",
  },
  ["Setup"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Setup.png",
    CostPlus = 0,
    Text = "Put a card from your hand on top of your draw pile.<br>It costs 0 until played.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Skewer"] = {
    Text = "Deal [7|10] damage X times.",
    Cost = -1,
    Color = "Green",
    Image = "Green-Skewer.png",
    Type = "Attack",
    Rarity = "Uncommon",
  },
  ["Tactician"] = {
    Cost = -2,
    Color = "Green",
    Image = "Green-Tactician.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Unplayable.<br>If this card is discarded from your hand, gain [@GE|@GE @GE].",
  },
  ["Terror"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Terror.png",
    CostPlus = 0,
    Text = "Apply 99 $Vulnerable.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Well-Laid Plans"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Well-LaidPlans.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the end of your turn, $Retain up to [1|2] [card|cards].",
  },
  ["A Thousand Cuts"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-AThousandCuts.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Whenever you play a card, deal [1|2] damage to ALL enemies.",
  },
  ["Adrenaline"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-Adrenaline.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Gain [@GE|@GE @GE].<br>Draw 2 cards.<br>$Exhaust.",
  },
  ["After Image"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-AfterImage.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "[|$Innate. <br>]Whenever you play a card, gain 1 $Block.",
  },
  ["Alchemize"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Alchemize.png",
    CostPlus = 0,
    Text = "Obtain a random potion.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Bullet Time"] = {
    Cost = 3,
    Color = "Green",
    Image = "Green-BulletTime.png",
    CostPlus = 2,
    Text = "You cannot draw additional cards this turn. Reduce the cost of all cards in your hand to 0 this turn.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Burst"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Burst.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "This turn, your next [Skill is|2 Skills are] played twice.",
  },
  ["Corpse Explosion"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-CorpseExplosion.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Apply [6|9] $Poison.<br>When the enemy dies, deal damage equal to its max HP to ALL enemies.",
  },
  ["Die Die Die"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-DieDieDie.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [13|17] damage to ALL enemies.<br>$Exhaust.",
  },
  ["Doppelganger"] = {
  	Cost = -1,
    Text = "Next turn, draw [X|X+1] cards and gain [X|X+1] @GE.<br>$Exhaust.",
    Color = "Green",
    Image = "Green-Doppelganger.png",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Envenom"] = {
    Cost = 2,
    Color = "Green",
    Image = "Green-Envenom.png",
    CostPlus = 1,
    Text = "Whenever an Attack deals unblocked damage, apply 1 $Poison.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Glass Knife"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-GlassKnife.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [8|12] damage twice. Decrease the damage of this card by 2 this combat.",
  },
  ["Grand Finale"] = {
    Cost = 0,
    Color = "Green",
    Image = "Green-GrandFinale.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Can only be played if there are no cards in your draw pile.<br>Deal [50|60] damage to ALL enemies.",
  },
  ["Malaise"] = {
  	Cost = -1,
    Text = "Enemy loses [X|X+1] $Strength. Apply [X|X+1] $Weak.<br>$Exhaust.",
    Color = "Green",
    Image = "Green-Malaise.png",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Nightmare"] = {
    Cost = 3,
    Color = "Green",
    Image = "Green-Nightmare.png",
    CostPlus = 2,
    Text = "Choose a card.<br>Next turn, add 3 copies of that card into your hand. $Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Phantasmal Killer"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-PhantasmalKiller.png",
    CostPlus = 0,
    Text = "Next turn, your Attacks deal double damage.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Storm of Steel"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-StormofSteel.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Discard your hand.<br>Add 1 {{C|Shiv}}[|+] into your hand for each card discarded.",
  },
  ["Tools of the Trade"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-ToolsoftheTrade.png",
    CostPlus = 0,
    Text = "At the start of your turn, draw 1 card and discard 1 card.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Unload"] = {
    Cost = 1,
    Color = "Green",
    Image = "Green-Unload.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [14|18] damage.<br>Discard all non-Attack cards in your hand.",
  },
  ["Wraith Form"] = {
    Cost = 3,
    Color = "Green",
    Image = "Green-WraithForm.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Gain [2|3] $Intangible.<br>At the end of your turn, lose 1 $Dexterity.",
  },
  ["Defend (Defect)"] = {
    Cost = 1,
    ID = "Defend (Defect)",
    Color = "Blue",
    Image = "Blue-Defend.png",
    Rarity = "Basic",
    Text = "Gain [5|8] $Block.",
    Type = "Skill",
    Link = "Defend (Defect)",
  },
  ["Strike (Defect)"] = {
    Cost = 1,
    ID = "Strike (Defect)",
    Color = "Blue",
    Image = "Blue-Strike.png",
    Rarity = "Basic",
    Text = "Deal [6|9] damage.",
    Type = "Attack",
    Link = "Strike (Defect)",
  },
  ["Dualcast"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Dualcast.png",
    CostPlus = 0,
    Text = "$Evoke your next Orb twice.",
    Type = "Skill",
    Rarity = "Basic",
  },
  ["Zap"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Zap.png",
    CostPlus = 0,
    Text = "$Channel 1 $Lightning.",
    Type = "Skill",
    Rarity = "Basic",
  },
  ["Ball Lightning"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-BallLightning.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|10] damage. $Channel 1 $Lightning.",
  },
  ["Barrage"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Barrage.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [4|6] damage for each $Channeled Orb.",
  },
  ["Beam Cell"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-BeamCell.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [3|4] damage.<br>Apply [1|2] $Vulnerable.",
  },
  ["Charge Battery"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-ChargeBattery.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [7|10] $Block.<br>Next turn, gain @BE.",
  },
  ["Claw"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-Claw.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [3|5] damage.<br>Increase the damage of ALL Claw cards by 2 this combat.",
  },
  ["Cold Snap"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-ColdSnap.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [6|9] damage. $Channel 1 $Frost.",
  },
  ["Compile Driver"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-CompileDriver.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|10] damage.<br>Draw 1 card for each unique Orb you have.",
  },
  ["Coolheaded"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Coolheaded.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "$Channel 1 $Frost.<br>Draw [1|2] [card|cards].",
  },
  ["Go for the Eyes"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-GofortheEyes.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [3|4] damage.<br>If the enemy intends to attack, apply [1|2] $Weak.",
  },
  ["Hologram"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Hologram.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [3|5] $Block.<br>Put a card from your discard pile into your hand.[<br>$Exhaust.|]",
  },
  ["Leap"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Leap.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [9|12] $Block.",
  },
  ["Rebound"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Rebound.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [9|12] damage.<br>Put the next card you play this turn on top of your draw pile.",
  },
  ["Recursion"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Recursion.png",
    CostPlus = 0,
    Text = "$Evoke your next Orb.<br>$Channel the Orb that was just $Evoked.",
    Type = "Skill",
    Rarity = "Common",
  },
  ["Stack"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Stack.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain $Block equal to the number of cards in your discard pile[|+3].",
  },
  ["Steam Barrier"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-SteamBarrier.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [6|8] $Block. Decrease this card's $Block by 1 this combat.",
  },
  ["Streamline"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Streamline.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [15|20] damage.<br>Reduce this card's cost by 1 this combat.",
  },
  ["Sweeping Beam"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-SweepingBeam.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [6|9] damage to ALL enemies.<br>Draw 1 card.",
  },
  ["TURBO"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-TURBO.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [@BE @BE|@BE @BE @BE].<br>Add a {{C|Void}} into your discard pile.",
  },
  ["Aggregate"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Aggregate.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain @BE for every [4|3] cards in your draw pile.",
  },
  ["Auto-Shields"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Auto-Shields.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "If you have no $Block, gain [11|15] $Block.",
  },
  ["Blizzard"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Blizzard.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal damage equal to [2|3] times the number of $Frost $Channeled this combat to ALL enemies.",
  },
  ["Boot Sequence"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-BootSequence.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Innate.<br>Gain [10|13] $Block.<br>$Exhaust.",
  },
  ["Bullseye"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Bullseye.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [8|11] damage.<br>Apply [2|3] $Lock On.",
  },
  ["Capacitor"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Capacitor.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Gain [2|3] $Orb slots.",
  },
  ["Chaos"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Chaos.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Channel [1|2] random [Orb|Orbs].",
  },
  ["Chill"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-Chill.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "[|$Innate. <br>]$Channel 1 $Frost for each enemy in combat.<br>$Exhaust.",
  },
  ["Consume"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Consume.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [2|3] $Focus.<br>Lose 1 $Orb slot.",
  },
  ["Darkness"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Darkness.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Channel 1 $Dark.[|<br>Trigger the passive ability of ALL $Dark orbs.]",
  },
  ["Defragment"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Defragment.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Gain [1|2] $Focus.",
  },
  ["Doom and Gloom"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-DoomandGloom.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [10|14] damage to ALL enemies.<br>$Channel 1 $Dark.",
  },
  ["Double Energy"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-DoubleEnergy.png",
    CostPlus = 0,
    Text = "Double your $Energy.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Equilibrium"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Equilibrium.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [13|16] $Block.<br>$Retain your hand this turn.",
  },
  ["FTL"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-FTL.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [5|6] damage. If you have played less than [3|4] cards this turn, draw 1 card.",
  },
  ["Force Field"] = {
    Cost = 4,
    Color = "Blue",
    Image = "Blue-ForceField.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Costs 1 less @BE for each Power card played this combat.<br>Gain [12|16] $Block.",
  },
  ["Fusion"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Fusion.png",
    CostPlus = 1,
    Text = "$Channel 1 $Plasma.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Genetic Algorithm"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-GeneticAlgorithm.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain 1 $Block. Permanently increase this card's $Block by [2|3].<br>$Exhaust.",
  },
  ["Glacier"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Glacier.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [7|10] $Block.<br>$Channel 2 $Frost.",
  },
  ["Heatsinks"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Heatsinks.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you play a Power card, draw [1|2] [card|cards].",
  },
  ["Hello World"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-HelloWorld.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "[|$Innate. <br>]At the start of your turn, add a random Common card into your hand.",
  },
  ["Loop"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Loop.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the start of your turn, trigger the passive ability of your next Orb [1 time|2 times].",
  },
  ["Melter"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Melter.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Remove all $Block from the enemy.<br>Deal [10|14] damage.",
  },
  ["Overclock"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-Overclock.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Draw [2|3] cards.<br>Add a {{C|Burn}} into your discard pile.",
  },
  ["Recycle"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Recycle.png",
    CostPlus = 0,
    Text = "$Exhaust a card.<br>Gain @BE equal to its cost.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Reinforced Body"] = {
  	Cost = -1,
    Text = "Gain [7|9] $Block X times.",
    Color = "Blue",
    Image = "Blue-ReinforcedBody.png",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Reprogram"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Reprogram.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Lose [1|2] $Focus. <br>Gain [1|2] $Strength. <br>Gain [1|2] $Dexterity.",
  },
  ["Rip and Tear"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-RipandTear.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [7|9] damage to a random enemy twice.",
  },
  ["Scrape"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Scrape.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [7|10] damage.<br>Draw [4|5] cards.<br>Discard all cards drawn this way that do not cost 0.",
  },
  ["Self Repair"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-SelfRepair.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the end of combat, heal [7|10] HP.",
  },
  ["Skim"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Skim.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Draw [3|4] cards.",
  },
  ["Static Discharge"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-StaticDischarge.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you receive unblocked attack damage, $Channel [1|2] $Lightning.",
  },
  ["Storm"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Storm.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "[|$Innate. <br>]Whenever you play a {{QueryLink|Cards|type:Power|Power}} card, $Channel 1 $Lightning.",
  },
  ["Sunder"] = {
    Cost = 3,
    Color = "Blue",
    Image = "Blue-Sunder.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [24|32] damage.<br>If this kills an enemy, gain @BE @BE @BE.",
  },
  ["Tempest"] = {
    Text = "$Channel [X|X+1] $Lightning.<br>$Exhaust.",
    Color = "Blue",
    Cost = -1,
    Image = "Blue-Tempest.png",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["White Noise"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-WhiteNoise.png",
    CostPlus = 0,
    Text = "Add a random Power card into your hand.<br>It costs 0 this turn.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["All for One"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-AllforOne.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [10|14] damage.<br>Put all cost 0 cards from your discard pile into your hand.",
  },
  ["Amplify"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-Amplify.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "This turn, your next [Power card is|2 Power cards are] played twice.",
  },
  ["Biased Cognition"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-BiasedCognition.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Gain [4|5] $Focus.<br>At the start of your turn, lose 1 $Focus.",
  },
  ["Buffer"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Buffer.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Prevent the next [time|2 times] you would lose HP.",
  },
  ["Core Surge"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-CoreSurge.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [11|15] damage.<br>Gain 1 $Artifact.<br>$Exhaust.",
  },
  ["Creative AI"] = {
    Cost = 3,
    Color = "Blue",
    Image = "Blue-CreativeAI.png",
    CostPlus = 2,
    Text = "At the start of your turn, add a random Power card into your hand.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Echo Form"] = {
    Cost = 3,
    Color = "Blue",
    Image = "Blue-EchoForm.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "[$Ethereal. <br>|]The first card you play each turn is played twice.",
  },
  ["Electrodynamics"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Electrodynamics.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "$Lightning now hits ALL enemies.<br>$Channel [2|3] $Lightning.",
  },
  ["Fission"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-Fission.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "[Remove|$Evoke] all your Orbs. Gain @BE and draw 1 card for each Orb [removed|$Evoked].<br>$Exhaust.",
  },
  ["Hyperbeam"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Hyperbeam.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [26|34] damage to ALL enemies.<br>Lose 3 $Focus.",
  },
  ["Machine Learning"] = {
    Cost = 1,
    Color = "Blue",
    Image = "Blue-MachineLearning.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "[|$Innate. <br>]At the start of your turn, draw 1 additional card.",
  },
  ["Meteor Strike"] = {
    Cost = 5,
    Color = "Blue",
    Image = "Blue-MeteorStrike.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [24|30] damage. <br>$Channel 3 $Plasma.",
  },
  ["Multi-Cast"] = {
  	Cost = -1,
    Text = "$Evoke your next Orb [X|X+1] times.",
    Color = "Blue",
    Image = "Blue-Multi-Cast.png",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Rainbow"] = {
    Cost = 2,
    Color = "Blue",
    Image = "Blue-Rainbow.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "$Channel 1 $Lightning.<br>$Channel 1 $Frost.<br>$Channel 1 $Dark.[<br>$Exhaust.|]",
  },
  ["Reboot"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-Reboot.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Shuffle ALL your cards into your draw pile.<br>Draw [4|6] cards.<br>$Exhaust.",
  },
  ["Seek"] = {
    Cost = 0,
    Color = "Blue",
    Image = "Blue-Seek.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Put [1|2] [card|cards] from your draw pile into your hand.<br>$Exhaust.",
  },
  ["Thunder Strike"] = {
    Cost = 3,
    Color = "Blue",
    Image = "Blue-ThunderStrike.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [7|9] damage to a random enemy for each $Lightning $Channeled this combat.",
  },
  ["Defend (Watcher)"] = {
    Cost = 1,
    ID = "Defend (Watcher)",
    Color = "Purple",
    Image = "Purple-Defend.png",
    Rarity = "Basic",
    Text = "Gain [5|8] $Block.",
    Type = "Skill",
    Link = "Defend (Watcher)",
  },
  ["Eruption"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Eruption.png",
    CostPlus = 1,
    Text = "Deal 9 damage. Enter $Wrath.",
    Type = "Attack",
    Rarity = "Basic",
  },
  ["Strike (Watcher)"] = {
    Cost = 1,
    ID = "Strike (Watcher)",
    Color = "Purple",
    Image = "Purple-Strike.png",
    Rarity = "Basic",
    Text = "Deal [6|9] damage.",
    Type = "Attack",
    Link = "Strike (Watcher)",
  },
  ["Vigilance"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Vigilance.png",
    Type = "Skill",
    Rarity = "Basic",
    Text = "Gain [8|12] $Block. <br>Enter $Calm.",
  },
  ["Bowling Bash"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-BowlingBash.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|10] damage for each enemy in combat.",
  },
  ["Consecrate"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-Consecrate.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [5|8] damage to ALL enemies.",
  },
  ["Crescendo"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Crescendo.png",
    CostPlus = 0,
    Text = "$Retain. <br>Enter $Wrath. <br>$Exhaust.",
    Type = "Skill",
    Rarity = "Common",
  },
  ["Crush Joints"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-CrushJoints.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [8|10] damage. If the last card played this combat was a {{QueryLink|Cards|type:Skill|Skill}}, apply [1|2] $Vulnerable.",
  },
  ["Cut Through Fate"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-CutThroughFate.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|9] damage. <br>$Scry [2|3]. <br>Draw 1 card.",
  },
  ["Empty Body"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-EmptyBody.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [7|10] $Block. Exit your $Stance.",
  },
  ["Empty Fist"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-EmptyFist.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [9|14] damage. Exit your $Stance.",
  },
  ["Evaluate"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Evaluate.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [6|10] $Block. Shuffle an {{C|Insight}} into your draw pile.",
  },
  ["Flurry of Blows"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-FlurryofBlows.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [4|6] damage.<br>Whenever you change $Stances, return this from the discard pile to your hand.",
  },
  ["Flying Sleeves"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-FlyingSleeves.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "$Retain. <br>Deal [4|6] damage twice.",
  },
  ["Follow-Up"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Follow-Up.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [7|11] damage. <br>If the previous card played was an Attack, gain @PE.",
  },
  ["Halt"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-Halt.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [3|4] $Block. <br>If you are in $Wrath, gain [9|14] additional $Block.",
  },
  ["Just Lucky"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-JustLucky.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "$Scry [1|2]. <br>Gain [2|3] $Block. <br>Deal [3|4] damage.",
  },
  ["Pressure Points"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-PressurePoints.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Apply [8|11] Mark. ALL enemies lose HP equal to their Mark.",
  },
  ["Prostrate"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-Prostrate.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [2|3] $Mantra. <br>Gain 4 $Block.",
  },
  ["Protect"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Protect.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "$Retain. Gain [12|16] $Block.",
  },
  ["Sash Whip"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-SashWhip.png",
    Type = "Attack",
    Rarity = "Common",
    Text = "Deal [8|10] damage. If the last card played this combat was an Attack, apply [1|2] $Weak.",
  },
  ["Third Eye"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-ThirdEye.png",
    Type = "Skill",
    Rarity = "Common",
    Text = "Gain [7|9] $Block. <br>$Scry [3|5].",
  },
  ["Tranquility"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Tranquility.png",
    CostPlus = 0,
    Text = "$Retain. <br>Enter $Calm. <br>$Exhaust.",
    Type = "Skill",
    Rarity = "Common",
  },
  ["Battle Hymn"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-BattleHymn.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "[|$Innate. <br>]At the start of each turn add a {{C|Smite}} into your hand.",
  },
  ["Carve Reality"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-CarveReality.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [6|10] damage. Add a {{C|Smite}} into your hand.",
  },
  ["Collect"] = {
  	Cost = -1,
    Text = "Put a {{C|Miracle|Miracle+}} into your hand at the start of your next [X|X+1] turns. $Exhaust",
    Color = "Purple",
    Image = "Purple-Collect.png",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Conclude"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Conclude.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [12|16] damage to ALL enemies. End your turn.",
  },
  ["Deceive Reality"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-DeceiveReality.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [4|7] $Block. <br>Add a {{C|Safety}} into your hand.",
  },
  ["Empty Mind"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-EmptyMind.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Exit your $Stance. Draw [2|3] cards.",
  },
  ["Fasting"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Fasting.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Gain [3|4] $Strength. <br>Gain [3|4] $Dexterity. <br>Gain 1 less @PE at the start of each turn.",
  },
  ["Fear No Evil"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-FearNoEvil.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [8|11] damage. If the enemy intends to Attack, enter $Calm.",
  },
  ["Foreign Influence"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-ForeignInfluence.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Choose 1 of 3 Attacks of any color to add to your hand.[ |It costs 0 this turn.] $Exhaust.",
  },
  ["Foresight"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Foresight.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the start of your turn, $Scry [3|4].",
  },
  ["Indignation"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Indignation.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "If you are in $Wrath, apply [3|5] $Vulnerable to ALL enemies, otherwise enter $Wrath.",
  },
  ["Inner Peace"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-InnerPeace.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "If you are in $Calm, draw [3|4] cards, otherwise Enter $Calm.",
  },
  ["Like Water"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-LikeWater.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "At the end of your turn, if you are in $Calm, gain [5|7] $Block.",
  },
  ["Meditate"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Meditate.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Put [1 card|2 cards] from your discard pile into your hand and $Retain [it|them]. Enter $Calm. End your turn.",
  },
  ["Mental Fortress"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-MentalFortress.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you switch $Stances, gain [4|6] $Block.",
  },
  ["Nirvana"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Nirvana.png",
    Type = "Power",
    Rarity = "Uncommon",
    Text = "Whenever you $Scry, gain [3|4] $Block.",
  },
  ["Perseverance"] = {
  	Cost = 1,
    Text = "$Retain. Gain [5|7] $Block. Whenever this card is $Retained, increase its $Block by [2|3].",
    Color = "Purple",
    Image = "Purple-Perseverance.png",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Pray"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Pray.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [3|4] $Mantra. Shuffle an {{C|Insight}} into your draw pile.",
  },
  ["Reach Heaven"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-ReachHeaven.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [10|15] damage. Shuffle a {{C|Through Violence}} into your draw pile.",
  },
  ["Rushdown"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Rushdown.png",
    CostPlus = 0,
    Text = "Whenever you enter $Wrath, draw 2 cards.",
    Type = "Power",
    Rarity = "Uncommon",
  },
  ["Sanctity"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Sanctity.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [6|9] $Block. <br>If the last card played this combat was a Skill, draw 2 cards.",
  },
  ["Sands of Time"] = {
    Cost = 4,
    Color = "Purple",
    Image = "Purple-SandsofTime.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "$Retain. <br>Deal [20|26] damage. <br>When $Retained, lower its cost by 1 this combat.",
  },
  ["Signature Move"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-SignatureMove.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Can only be played if this is the only Attack in your hand. <br>Deal [30|40] damage.",
  },
  ["Simmering Fury"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-SimmeringFury.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "At the start of your next turn, enter $Wrath and draw [2|3] cards.",
  },
  ["Study"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Study.png",
    CostPlus = 1,
    Text = "At the end of your turn, shuffle an {{C|Insight}} into your draw pile.",
    Type = "Power",
    Rarity = "Uncommon",
  },
  ["Swivel"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Swivel.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [8|11] $Block. <br>The next Attack you play costs 0.",
  },
  ["Talk to the Hand"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-TalktotheHand.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [5|7] damage. Whenever you attack this enemy, gain [2|3] $Block. <br>$Exhaust.",
  },
  ["Tantrum"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Tantrum.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal 3 damage [3|4] times. Enter $Wrath. Shuffle this card into your draw pile.",
  },
  ["Wallop"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Wallop.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [9|12] damage. Gain $Block equal to unblocked damage dealt.",
  },
  ["Wave of the Hand"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-WaveoftheHand.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Whenever you gain $Block this turn, apply [1|2] $Weak to ALL enemies.",
  },
  ["Weave"] = {
    Cost = 0,
    Color = "Purple",
    Image = "Purple-Weave.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [4|6] damage. Whenever you $Scry, return this from the discard pile to your hand.",
  },
  ["Wheel Kick"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-WheelKick.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [15|20] damage. Draw 2 cards.",
  },
  ["Windmill Strike"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-WindmillStrike.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "$Retain. <br>Deal [7|10] damage. <br>When $Retained, increase its damage by [4|5] this combat.",
  },
  ["Worship"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-Worship.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "[|$Retain. ]Gain 5 $Mantra.",
  },
  ["Wreath of Flame"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-WreathofFlame.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Your next Attack deals [5|8] additional damage.",
  },
  ["Alpha"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Alpha.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "[|$Innate. ]Shuffle a {{C|Beta}} into your draw pile. $Exhaust.",
  },
  ["Blasphemy"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Blasphemy.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "[|$Retain. ]Enter $Divinity. Die next turn. $Exhaust",
  },
  ["Brilliance"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Brilliance.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [12|16] damage. Deals additional damage equal to $Mantra gained this combat.",
  },
  ["Conjure Blade"] = {
    Text = "Shuffle an {{C|Expunger}}[| with X+1] into your draw pile. <br>$Exhaust.",
    Color = "Purple",
    Cost = -1,
    Image = "Purple-ConjureBlade.png",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Deus Ex Machina"] = {
    Cost = -2,
    Text = "$Unplayable. <br>When you draw this card, add [2|3] {{C|Miracle|Miracles}} to your hand and $Exhaust.",
    Color = "Purple",
    Image = "Purple-DeusExMachina.png",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Deva Form"] = {
    Cost = 3,
    Color = "Purple",
    Image = "Purple-DevaForm.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "[$Ethereal.<br>|]At the start of your turn, gain @PE <br>and increase this gain by 1.",
  },
  ["Devotion"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Devotion.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "At the start of your turn, gain [2|3] $Mantra.",
  },
  ["Establishment"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Establishment.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "[|$Innate. ]Whenever a card is $Retained, lower its cost by 1.",
  },
  ["Judgment"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Judgment.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "If the enemy has [30|40] or less HP, set their HP to 0.",
  },
  ["Lesson Learned"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-LessonLearned.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [10|13] damage. <br>If $Fatal, $Upgrade a random card in your deck. <br>$Exhaust.",
  },
  ["Master Reality"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-MasterReality.png",
    CostPlus = 0,
    Text = "Whenever a card is created during combat, $Upgrade it.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Omniscience"] = {
    Cost = 4,
    Color = "Purple",
    Image = "Purple-Omniscience.png",
    CostPlus = 3,
    Text = "Choose a card in your draw pile. Play the chosen card twice and $Exhaust it. $Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Ragnarok"] = {
    Cost = 3,
    Color = "Purple",
    Image = "Purple-Ragnarok.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [5|6] damage to a random enemy [5|6] times.",
  },
  ["Scrawl"] = {
    Cost = 1,
    Color = "Purple",
    Image = "Purple-Scrawl.png",
    CostPlus = 0,
    Text = "Draw cards until your hand is full. <br>$Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Spirit Shield"] = {
    Cost = 2,
    Color = "Purple",
    Image = "Purple-SpiritShield.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Gain [3|4] $Block for each card in your hand.",
  },
  ["Vault"] = {
    Cost = 3,
    Color = "Purple",
    Image = "Purple-Vault.png",
    CostPlus = 2,
    Text = "Take an extra turn after this one. <br>End your turn. <br>$Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Wish"] = {
    Cost = 3,
    Color = "Purple",
    Image = "Purple-Wish.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Choose one: Gain [6|8] $Plated Armor, [3|4] $Strength, or [25|30] Gold. $Exhaust.",
  },
  ["Become Almighty"] = {
    Color = "Colorless",
    Cost = -2,
    Image = "Colorless-BecomeAlmighty.png",
    Type = "Power",
    Rarity = "Special",
    Text = "Gain [3|4] $Strength.",
  },
  ["Fame and Fortune"] = {
    Color = "Colorless",
    Cost = -2,
    Image = "Colorless-FameandFortune.png",
    Type = "Skill",
    Rarity = "Special",
    Text = "Gain [25|30] Gold",
  },
  ["Live Forever"] = {
    Color = "Colorless",
    Cost = -2,
    Image = "Colorless-LiveForever.png",
    Type = "Power",
    Rarity = "Special",
    Text = "Gain [6|8] $Plated Armor.",
  },
  ["Burn"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Colorless-Burn.png",
    Type = "Status",
    Rarity = "Common",
    Text = "$Unplayable.<br>At the end of your turn, take [2|4] damage.",
  },
  ["Dazed"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Colorless-Dazed.png",
    Rarity = "Common",
    Text = "$Unplayable.<br>$Ethereal.",
    Type = "Status",
    NoUpgrade = true,
  },
  ["Slimed"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Slimed.png",
    Rarity = "Common",
    Text = "$Exhaust.",
    Type = "Status",
    NoUpgrade = true,
  },
  ["Void"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Colorless-Void.png",
    Rarity = "Common",
    Text = "$Unplayable.<br>$Ethereal.<br>Whenever this card is drawn, lose 1 $Energy.",
    Type = "Status",
    NoUpgrade = true,
  },
  ["Wound"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Colorless-Wound.png",
    Rarity = "Common",
    Text = "$Unplayable.",
    Type = "Status",
    NoUpgrade = true,
  },
  ["Bandage Up"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-BandageUp.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Heal [4|6] HP.<br>$Exhaust.",
  },
  ["Blind"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Blind.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply 2 $Weak[| to ALL enemies].",
  },
  ["Dark Shackles"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-DarkShackles.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Enemy loses [9|15] $Strength this turn.<br>$Exhaust.",
  },
  ["Deep Breath"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-DeepBreath.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Shuffle your discard pile into your draw pile.<br>Draw [1 card|2 cards].",
  },
  ["Discovery"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Discovery.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Choose 1 of 3 random cards to add into your hand. It costs 0 this turn.[<br>$Exhaust.|]",
  },
  ["Dramatic Entrance"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-DramaticEntrance.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "$Innate.<br>Deal [8|12] damage to ALL enemies.<br>$Exhaust.",
  },
  ["Enlightenment"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Enlightenment.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Reduce the cost of all cards in your hand to 1 this [turn|combat].",
  },
  ["Finesse"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Finesse.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [2|4] $Block.<br>Draw 1 card.",
  },
  ["Flash of Steel"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-FlashofSteel.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [3|6] damage.<br>Draw 1 card.",
  },
  ["Forethought"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Forethought.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Put [a card|any number of cards] from your hand to the bottom of your draw pile. [It costs|They cost] 0 until played.",
  },
  ["Good Instincts"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-GoodInstincts.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [6|9] $Block.",
  },
  ["Impatience"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Impatience.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "If you have no Attacks in your hand, draw [2|3] cards.",
  },
  ["Jack of All Trades"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-JackofAllTrades.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Add [1|2] random Colorless [card|cards] into your hand.<br>$Exhaust.",
  },
  ["Madness"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Madness.png",
    CostPlus = 0,
    Text = "Reduce the cost of a random card in your hand to 0 this combat.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Uncommon",
  },
  ["Mind Blast"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-MindBlast.png",
    CostPlus = 1,
    Text = "$Innate.<br>Deal damage equal to the number of cards in your draw pile.",
    Type = "Attack",
    Rarity = "Uncommon",
  },
  ["Panacea"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Panacea.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [1|2] $Artifact.<br>$Exhaust.",
  },
  ["Panic Button"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-PanicButton.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Gain [30|40] $Block. You cannot gain $Block from cards for 2 turns.<br>$Exhaust.",
  },
  ["Purity"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Purity.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "$Exhaust up to [3|5] cards in your hand.<br>$Exhaust.",
  },
  ["Swift Strike"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-SwiftStrike.png",
    Type = "Attack",
    Rarity = "Uncommon",
    Text = "Deal [7|10] damage.",
  },
  ["Trip"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Trip.png",
    Type = "Skill",
    Rarity = "Uncommon",
    Text = "Apply 2 $Vulnerable[| to ALL enemies].",
  },
  ["Apotheosis"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-Apotheosis.png",
    CostPlus = 1,
    Text = "$Upgrade ALL your cards for the rest of combat.<br>$Exhaust.",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Chrysalis"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-Chrysalis.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Shuffle [3|5] random Skills into your draw pile. They cost 0 this combat.<br>$Exhaust.",
  },
  ["Hand of Greed"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-HandofGreed.png",
    Type = "Attack",
    Rarity = "Rare",
    Text = "Deal [20|25] damage.<br>If $Fatal, gain [20|25] Gold.",
  },
  ["Magnetism"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-Magnetism.png",
    CostPlus = 1,
    Text = "At the start of your turn, add a random Colorless card into your hand.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Master of Strategy"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-MasterofStrategy.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Draw [3|4] cards.<br>$Exhaust.",
  },
  ["Mayhem"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-Mayhem.png",
    CostPlus = 1,
    Text = "At the start of your turn, play the top card of your draw pile.",
    Type = "Power",
    Rarity = "Rare",
  },
  ["Metamorphosis"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-Metamorphosis.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Shuffle [3|5] random Attacks into your draw pile. They cost 0 this combat.<br>$Exhaust.",
  },
  ["Panache"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Panache.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Every time you play 5 cards in a single turn, deal [10|14] damage to ALL enemies.",
  },
  ["Sadistic Nature"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-SadisticNature.png",
    Type = "Power",
    Rarity = "Rare",
    Text = "Whenever you apply a debuff to an enemy, they take [5|7] damage.",
  },
  ["Secret Technique"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-SecretTechnique.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Put a Skill from your draw pile into your hand.[<br>$Exhaust.|]",
  },
  ["Secret Weapon"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-SecretWeapon.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Put an Attack from your draw pile into your hand.[<br>$Exhaust.|]",
  },
  ["The Bomb"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-TheBomb.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "At the end of 3 turns, deal [40|50] damage to ALL enemies.",
  },
  ["Thinking Ahead"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-ThinkingAhead.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Draw 2 cards.<br>Put a card from your hand on top of your draw pile.[<br>$Exhaust.|]",
  },
  ["Transmutation"] = {
  	Cost = -1,
    Text = "Add X random[| $Upgraded] Colorless cards into your hand. They cost 0 this turn.<br>$Exhaust.",
    Color = "Colorless",
    Image = "Colorless-Transmutation.png",
    Type = "Skill",
    Rarity = "Rare",
  },
  ["Violence"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Violence.png",
    Type = "Skill",
    Rarity = "Rare",
    Text = "Put [3|4] random Attacks from your draw pile into your hand.<br>$Exhaust.",
  },
  ["Apparition"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Apparition.png",
    Type = "Skill",
    Rarity = "Special",
    Text = "[$Ethereal. <br>|]Gain 1 $Intangible. <br>$Exhaust.",
  },
  ["Beta"] = {
    Cost = 2,
    Color = "Colorless",
    Image = "Colorless-Beta.png",
    CostPlus = 1,
    Text = "Shuffle an {{C|Omega}} into draw pile. <br>$Exhaust.",
    Type = "Skill",
    Rarity = "Special",
  },
  ["Bite"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Bite.png",
    Type = "Attack",
    Rarity = "Special",
    Text = "Deal [7|8] damage.<br>Heal [2|3] HP.",
  },
  ["Expunger"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Expunger.png",
    Type = "Attack",
    Rarity = "Special",
    Text = "Deal [9|15] damage X times.",
  },
  ["Insight"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Insight.png",
    Type = "Skill",
    Rarity = "Special",
    Text = "$Retain. <br>Draw [2|3] cards. <br>$Exhaust.",
  },
  ["J.A.X."] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-J.A.X..png",
    Type = "Skill",
    Rarity = "Special",
    Text = "Lose 3 HP.<br>Gain [2|3] $Strength.",
  },
  ["Miracle"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Miracle.png",
    Type = "Skill",
    Rarity = "Special",
    Text = "$Retain. <br>Gain [@PE|@PE @PE]. <br>$Exhaust.",
  },
  ["Omega"] = {
    Cost = 3,
    Color = "Colorless",
    Image = "Colorless-Omega.png",
    Type = "Power",
    Rarity = "Special",
    Text = "At the end of your turn, deal [50|60] damage to ALL enemies.",
  },
  ["Ritual Dagger"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-RitualDagger.png",
    Type = "Attack",
    Rarity = "Special",
    Text = "Deal 15 damage. If $Fatal, permanently increase this card's damage by [3|5].<br>$Exhaust.",
  },
  ["Safety"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Safety.png",
    Type = "Skill",
    Rarity = "Special",
    Text = "$Retain. <br>Gain [12|16] $Block. <br>$Exhaust.",
  },
  ["Shiv"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-Shiv.png",
    Type = "Attack",
    Rarity = "Special",
    Text = "Deal [4|6] damage.<br>$Exhaust.",
  },
  ["Smite"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Colorless-Smite.png",
    Type = "Attack",
    Rarity = "Special",
    Text = "$Retain. <br>Deal [12|16] damage. <br>$Exhaust.",
  },
  ["Through Violence"] = {
    Cost = 0,
    Color = "Colorless",
    Image = "Colorless-ThroughViolence.png",
    Type = "Attack",
    Rarity = "Special",
    Text = "$Retain. <br>Deal [20|30] damage. <br>$Exhaust.",
  },
  ["Ascender's Bane"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-AscendersBane.png",
    Rarity = "Curse",
    Text = "$Unplayable. <br>$Ethereal. <br>Cannot be removed from your deck.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Clumsy"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Clumsy.png",
    Rarity = "Curse",
    Text = "$Unplayable. <br>$Ethereal.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Curse of the Bell"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-CurseoftheBell.png",
    Rarity = "Curse",
    Text = "$Unplayable. <br>Cannot be removed from your deck.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Decay"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Decay.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>At the end of your turn, take 2 damage.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Doubt"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Doubt.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>At the end of your turn, gain 1 $Weak.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Injury"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Injury.png",
    Rarity = "Curse",
    Text = "$Unplayable.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Necronomicurse"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Necronomicurse.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>There is no escape from this curse.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Normality"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Normality.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>While in hand, you cannot play more than 3 cards this turn.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Pain"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Pain.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>While in hand, lose 1 HP when other cards are played.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Parasite"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Parasite.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>If transformed or removed from your deck, lose 3 Max HP.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Pride"] = {
    Cost = 1,
    Color = "Colorless",
    Image = "Curse-Pride.png",
    Rarity = "Curse",
    Text = "$Innate.<br>At the end of your turn, put a copy of this card on top of your draw pile. $Exhaust.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Regret"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Regret.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>At the end of your turn, lose HP equal to the number of cards in your hand.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Shame"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Shame.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>At the end of your turn, gain 1 $Frail.",
    Type = "Curse",
    NoUpgrade = true,
  },
  ["Writhe"] = {
    Cost = -2,
    Color = "Colorless",
    Image = "Curse-Writhe.png",
    Rarity = "Curse",
    Text = "$Unplayable.<br>$Innate.",
    Type = "Curse",
    NoUpgrade = true,
  }
}

local formatted = {}
for name, card in pairs(all_data) do
	card.EditLink = "Module:Cards/data"
	formatted[name] = card
end

return formatted