return {
  ["Attack Potion"] = {
    Text = "Choose 1 of 3 random {{QueryLink|Cards|type:Attack|Attack}} cards to add<:two copies of it> to your hand. <It costs:They cost> 0 this turn.",
    Image = "AttackPotion.png",
    Rarity = "Common",
    Code = "$Attack Potion",
  },
  ["Blessing of the Forge"] = {
    Text = "$Upgrade all cards in your hand for the rest of combat.",
    Image = "BlessingoftheForge.png",
    Rarity = "Common",
    Code = "$Blessing of the Forge",
  },
  ["Block Potion"] = {
    Text = "Gain <12:24> $Block.",
    Image = "BlockPotion.png",
    Rarity = "Common",
    Code = "$Block Potion",
  },
  ["Colorless Potion"] = {
    Text = "Choose 1 of 3 random {{QueryLink|Cards|color:Colorless|Colorless}} cards to add<:2 copies of> to your hand. <It costs:They cost> 0 this turn.",
    Image = "ColorlessPotion.png",
    Rarity = "Common",
    Code = "$Colorless Potion",
  },
  ["Dexterity Potion"] = {
    Text = "Gain <2:4> $Dexterity.",
    Image = "DexterityPotion.png",
    Rarity = "Common",
    Code = "$Dexterity Potion",
  },
  ["Energy Potion"] = {
    Text = "Gain <2:4> $Energy.",
    Image = "EnergyPotion.png",
    Rarity = "Common",
    Code = "$Energy Potion",
  },
  ["Explosive Potion"] = {
    Text = "Deal <10:20> damage to all enemies.",
    Image = "ExplosivePotion.png",
    Rarity = "Common",
    Code = "$Explosive Potion",
  },
  ["Fear Potion"] = {
    Text = "Apply <3:6> $Vulnerable to target enemy.",
    Image = "FearPotion.png",
    Rarity = "Common",
    Code = "$Fear Potion",
  },
  ["Fire Potion"] = {
    Text = "Deal <20:40> damage to target enemy.",
    Image = "FirePotion.png",
    Rarity = "Common",
    Code = "$Fire Potion",
  },
  ["Flex Potion"] = {
    Text = "Gain <5:10> $Strength. At the end of your turn, lose <5:10> $Strength.",
    Image = "FlexPotion.png",
    Rarity = "Common",
    Code = "$Flex Potion",
  },
  ["Power Potion"] = {
    Text = "Choose 1 of 3 random {{QueryLink|Cards|type:Power|Power}} cards to add<:two copies of it> to your hand. <It costs:They cost> 0 this turn.",
    Image = "PowerPotion.png",
    Rarity = "Common",
    Code = "$Power Potion",
  },
  ["Skill Potion"] = {
    Text = "Choose 1 of 3 random {{QueryLink|Cards|type:Skill|Skill}} cards to add<:two copies of> to your hand. <It costs:They cost> 0 this turn.",
    Image = "SkillPotion.png",
    Rarity = "Common",
    Code = "$Skill Potion",
  },
  ["Speed Potion"] = {
    Text = "Gain <5:10> $Dexterity. At the end of your turn, lose <5:10> $Dexterity.",
    Image = "SpeedPotion.png",
    Rarity = "Common",
    Code = "$Speed Potion",
  },
  ["Strength Potion"] = {
    Text = "Gain <2:4> $Strength.",
    Image = "StrengthPotion.png",
    Rarity = "Common",
    Code = "$Strength Potion",
  },
  ["Swift Potion"] = {
    Text = "Draw <3:6> cards.",
    Image = "SwiftPotion.png",
    Rarity = "Common",
    Code = "$Swift Potion",
  },
  ["Weak Potion"] = {
    Text = "Apply <3:6> $Weak to target enemy.",
    Image = "WeakPotion.png",
    Rarity = "Common",
    Code = "$Weak Potion",
  },
  ["Blood Potion"] = {
    Text = "Heal for <20%:40%> of your Max HP.",
    Image = "BloodPotion.png",
    Character = "Ironclad",
    Rarity = "Common",
    Code = "$Blood Potion",
  },
  ["Poison Potion"] = {
    Text = "Apply <6:12> $Poison to target enemy.",
    Image = "PoisonPotion.png",
    Character = "Silent",
    Rarity = "Common",
    Code = "$Poison Potion",
  },
  ["Focus Potion"] = {
    Text = "Gain <2:4> $Focus.",
    Image = "FocusPotion.png",
    Character = "Defect",
    Rarity = "Common",
    Code = "$Focus Potion",
  },
  ["Bottled Miracle"] = {
    Text = "Add <2:4> {{C|Miracle|Miracles}} to your hand.",
    Image = "BottledMiracle.png",
    Character = "Watcher",
    Rarity = "Common",
    Code = "$Bottled Miracle",
  },
  ["Ancient Potion"] = {
    Text = "Gain <1:2> $Artifact.",
    Image = "AncientPotion.png",
    Rarity = "Uncommon",
    Code = "$Ancient Potion",
  },
  ["Distilled Chaos"] = {
    Text = "Play the top <3:6> cards of your draw pile.",
    Image = "DistilledChaos.png",
    Rarity = "Uncommon",
    Code = "$Distilled Chaos",
  },
  ["Duplication Potion"] = {
    Text = "This turn, your next <card is:two cards are> played twice.",
    Image = "DuplicationPotion.png",
    Rarity = "Uncommon",
    Code = "$Duplication Potion",
  },  
  ["Essence of Steel"] = {
    Text = "Gain <4:8> $Plated Armor.",
    Image = "EssenceofSteel.png",
    Rarity = "Uncommon",
    Code = "$Essence of Steel",
  },
  ["Gambler's Brew"] = {
    Text = "Discard any number of cards, then draw that many.",
    Image = "GamblersBrew.png",
    Rarity = "Uncommon",
    Code = "$Gambler's Brew",
  },
  ["Liquid Bronze"] = {
    Text = "Gain <3:6> $Thorns.",
    Image = "LiquidBronze.png",
    Rarity = "Uncommon",
    Code = "$Liquid Bronze",
  },
  ["Liquid Memories"] = {
    Text = "Choose <a card:2 cards> in your discard pile and return it to your hand. <It costs:They cost> 0 this turn.",
    Image = "LiquidMemories.png",
    Rarity = "Uncommon",
    Code = "$Liquid Memories",
  },
  ["Regen Potion"] = {
    Text = "Gain <5:10> $Regeneration.",
    Image = "RegenPotion.png",
    Rarity = "Uncommon",
    Code = "$Regen Potion",
  },
  ["Elixir"] = {
    Text = "$Exhaust any number of cards in your hand.",
    Image = "Elixir.png",
    Character = "Ironclad",
    Rarity = "Uncommon",
    Code = "$Elixir",
  },
  ["Cunning Potion"] = {
    Text = "Add <3:6> {{C|Shiv|Shivs+}} to your hand.",
    Image = "CunningPotion.png",
    Character = "Silent",
    Rarity = "Uncommon",
    Code = "$Cunning Potion",
  },
  ["Potion of Capacity"] = {
    Text = "Gain <2:4> $Orb slots.",
    Image = "PotionOfCapacity.png",
    Character = "Defect",
    Rarity = "Uncommon",
    Code = "$Potion of Capacity",
  },
  ["Stance Potion"] = {
    Text = "Enter $Calm or $Wrath.",
    Image = "StancePotion.png",
    Character = "Watcher",
    Rarity = "Uncommon",
    Code = "$Stance Potion",
  },
  ["Cultist Potion"] = {
    Text = "Gain <1:2> $Ritual.",
    Image = "CultistPotion.png",
    Rarity = "Rare",
    Code = "$Cultist Potion",
  },
  ["Entropic Brew"] = {
    Text = "Fill all your empty potion slots with random potions.",
    Image = "EntropicBrew.png",
    Rarity = "Rare",
    Code = "$Entropic Brew",
  },
  ["Fairy in a Bottle"] = {
    Text = "When you would die, heal to <30%:60%> of your Max HP instead and discard this potion.",
    Image = "FairyinaBottle.png",
    Rarity = "Rare",
    Code = "$Fairy in a Bottle",
  },
  ["Fruit Juice"] = {
    Text = "Gain <5:10> Max HP.",
    Image = "FruitJuice.png",
    Rarity = "Rare",
    Code = "$Fruit Juice",
  },
    ["Smoke Bomb"] = {
    Text = "Escape from a non-boss combat. Receive no rewards.",
    Image = "SmokeBomb.png",
    Rarity = "Rare",
    Code = "$Smoke Bomb",
  },
	["Snecko Oil"] = {
    Text = "Draw <5:10> [[Cards]]. Randomize the cost of cards in your hand",
    Image = "SneckoOil.png",
    Rarity = "Rare",
    Code = "$Snecko Oil",
  },
  ["Heart of Iron"] = {
    Text = "Gain <6:12> $Metallicize.",
    Image = "HeartofIron.png",
    Character = "Ironclad",
    Rarity = "Rare",
    Code = "$Heart of Iron",
  },
  ["Ghost in a Jar"] = {
    Text = "Gain <1:2> $Intangible.",
    Image = "GhostinaJar.png",
    Character = "Silent",
    Rarity = "Rare",
    Code = "$Ghost in a Jar",
  },
  ["Essence of Darkness"] = {
    Text = "Channel <1:2> $Dark for each orb slot.",
    Image = "EssenceOfDarkness.png",
    Character = "Defect",
    Rarity = "Rare",
    Code = "$Essence of Darkness",
  },
  ["Ambrosia"] = {
    Text = "Enter $Divinity.",
    Image = "Ambrosia.png",
    Character = "Watcher",
    Rarity = "Rare",
    Code = "$Ambrosia",
  },
}