local all_powers = {
    -- Common Effects
    ["Artifact"] = {
      Code = "$Artifact",
      Text = "Negates X debuffs.",
      Link = "Artifact",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_Artifact.png",
    },
    ["Buffer"] = {
      Code = "$Buffer",
      Text = "Prevent the next X times you would lose HP.",
      Link = "Buffer",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_Buffer.png",
    },
    ["Confused"] = {
      Code = "$Confused",
      Text = "Whenever you draw a card, randomize its cost.",
      Link = "Snecko_Eye",
      Stacks = "Does not stack",
      Type = "Debuff",
      Image = "Icon_Confused.png",
    },
    ["Dexterity"] = {
      Code = "$Dexterity",
      Text = "Increase $Block gained from cards by X.",
      Link = "Dexterity",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Dexterity.png",
    },
    ["Dexterity Down"] = {
      Code = "$Dexterity Down",
      Text = "At the end of this turn, lose X $Dexterity.",
      Link = "Debuffs#Dexterity_Down",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_StrengthDown.png",
    },
    ["Draw Card"] = {
      Code = "$Draw Card",
      Text = "Draw X additional cards next turn.",
      Link = "Buffs#Draw_Card",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_DrawCard.png",
    },
    ["Frail"] = {
      Code = "$Frail",
      Text = "Gain 25% less $Block from cards for X turns.",
      Link = "Debuffs#Frail",
      Stacks = "Duration",
      Type = "Debuff",
      Image = "Icon_Frail.png",
    },
    ["Intangible"] = {
      Code = "$Intangible",
      -- Ingame text does not tell it lasts X turns
      Text = "Reduce ALL damage taken and HP loss to 1.",
      Link = "Buffs#Intangible",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_Intangible.png",
    },
    ["Next Turn Block"] = {
      Code = "$Next Turn Block",
      Text = "Gain X $Block next turn.",
      Link = "Dodge_And_Roll",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_NextTurnBlock.png",
    },
    ["No Draw"] = {
      Code = "$No Draw",
      Text = "You may not draw additional cards this turn.",
      Link = "Debuffs#No_Draw",
      Stacks = "Does not stack",
      Type = "Debuff",
      Image = "Icon_NoDraw.png",
    },
    ["Plated Armor"] = {
      Code = "$Plated Armor",
      Text = "At the end of your turn, receive X $Block. Receiving unblocked damage reduces $Plated Armor by 1.",
      Link = "Plated Armor",
      Stacks = "Intensity and Counter",
      Type = "Buff",
      Image = "Icon_PlatedArmor.png",
    },
    ["Regen"] = {
      Code = "$Regen",
      Text = "Regen heals X HP at the end of your turn. <br>Each turn, $Regen is reduced by 1.",
      Link = "Buffs#Regen",
      Stacks = "Intensity and Duration",
      Type = "Buff",
      Image = "Icon_Regen.png",
    },
    ["Ritual"] = {
      Code = "$Ritual",
      Text = "Gain X $Strength every turn.",
      Link = "Buffs#Ritual",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Ritual.png",
    },
    ["Shackled"] = {
      Code = "$Shackled",
      Text = "At the end of its turn, gains X $Strength.",
      Link = "Strength#Negative Strength",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_Shackled.png",
    },
    ["Strength"] = {
      Code = "$Strength",
      Text = "Increases attack damage by X.",
      Link = "Strength",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Strength.png",
    },
    ["Strength Down"] = {
      Code = "$Strength Down",
      Text = "At the end of this turn, lose X $Strength.",
      Link = "Strength#Negative Strength",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_StrengthDown.png",
    },
    ["Thorns"] = {
      Image = "Icon_Thorns.png",
      Text = "Inflict X damage on the attacker when hit.",
      Code = "$Thorns",
      Stacks = "Intensity",
      Type = "Buff",
      Link = "Buffs#Thorns",
    },
    ["Vigor"] = {
      Code = "$Vigor",
      Text = "Your next attack deals X additional damage per hit.",
      Link = "Wreath_Of_Fire",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Vigor.png",
    },
    ["Vulnerable"] = {
      Code = "$Vulnerable",
      Text = "Receive 50% more damage from '''Attacks''' for X turns.",
      Link = "Vulnerable",
      Stacks = "Duration",
      Type = "Debuff",
      Image = "Icon_Vulnerable.png",
    },
    ["Weak"] = {
      Code = "$Weak",
      Text = "'''Attacks''' deal 25% less damage for X turns.",
      Link = "Weak",
      Stacks = "Duration",
      Type = "Debuff",
      Image = "Icon_Weak.png",
    },

    -- Ironclad Effects
    ["Double Tap"] = {
      Code = "$Double Tap",
      Text = "Your next X {{QueryLink|Cards|type:Attack|Attacks}} are played twice this turn.",
      Link = "Double_Tap",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_DoubleTap.png",
    },
    ["Flame Barrier"] = {
      Code = "$Flame Barrier",
      -- Ingame text does not specify Flame Barrier lasts 1 turn
      Text = "When attacked, deals X damage back.",
      Link = "Flame_Barrier",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_FlameBarrier.png",
    },
    ["Rage"] = {
      Code = "$Rage",
      Text = "Whenever you play an {{QueryLink|Cards|type:Attack|Attack}} this turn, gain X $Block.",
      Link = "Rage",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Anger.png",
    },

    -- Ironclad Powers
    ["Barricade"] = {
      Code = "$Barricade",
      Text = " $Block is not removed at the beginning of your turn.",
      Link = "Barricade",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Barricade.png",
    },
    ["Berserk"] = {
      Code = "$Berserk",
      Text = "At the start of your turn, gain X @RE '''Energy'''.",
      Link = "Berserk",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Berserk.png",
    },
    ["Brutality"] = {
      Code = "$Brutality",
      Text = "At the start of your turn, lose X HP and draw X cards.",
      Link = "Brutality",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Brutality.png",
    },
    ["Combust"] = {
      Code = "$Combust",
      Text = "At the end of your turn, lose X HP and deal damage to ALL enemies.",
      Link = "Combust",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Combust.png",
    },
    ["Corruption"] = {
      Code = "$Corruption",
      Text = "{{QueryLink|Cards|type:Skill|Skills}} cost 0. Whenever you play a {{QueryLink|Cards|type:Skill|Skill}}, $Exhaust it.",
      Link = "Corruption",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Corruption.png",
    },
    ["Dark Embrace"] = {
      Code = "$Dark Embrace",
      Text = "Whenever a card is $Exhausted, draw X cards.",
      Link = "Dark_Embrace",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_DarkEmbrace.png",
    },
    ["Demon Form"] = {
      Code = "$Demon Form",
      Text = "At the start of your turn, gain X $Strength.",
      Link = "Demon_Form",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_DemonForm.png",
    },
    ["Evolve"] = {
      Code = "$Evolve",
      Text = "Whenever you draw a {{QueryLink|Cards|type:Status|Status}} card, draw X cards.",
      Link = "Evolve",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Evolve.png",
    },
    ["Feel No Pain"] = {
      Code = "$Feel No Pain",
      Text = "Whenever you $Exhaust a card, gain X $Block.",
      Link = "Feel No Pain",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_FeelNoPain.png",
    },
    ["Fire Breathing"] = {
      Code = "$Fire Breathing",
      Text = "Whenever you draw a {{QueryLink|Cards|type:Status|Status}} or {{QueryLink|Cards|type:Curse|Curse}} card, deal X damage to ALL enemies.",
      Link = "Fire_Breathing",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_FireBreathing.png",
    },
    ["Juggernaut"] = {
      Code = "$Juggernaut",
      Text = "Whenever you gain $Block, deal X damage to a random enemy.",
      Link = "Juggernaut",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Juggernaut.png",
    },
    ["Metallicize"] = {
      Code = "$Metallicize",
      Text = "At the end of every turn, gain X $Block.",
      Link = "Metallicize",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Metallicize.png",
    },
    ["Rupture"] = {
      Code = "$Rupture",
      Text = "Whenever you lose HP from a card, gain X $Strength.",
      Link = "Rupture",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Rupture.png",
    },

    -- Silent Effects
    ["Blur"] = {
      Code = "$Blur",
      Text = "$Block is not removed at the beginning of your next X turns.",
      Link = "Blur",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_Blur.png",
    },
    ["Burst"] = {
      Code = "$Burst",
      Text = "Your next X {{QueryLink|Cards|type:Skill|Skills}} are played twice this turn.",
      Link = "Burst",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_Burst.png",
    },
    ["Corpse Explosion"] = {
      Code = "$Corpse Explosion",
      Text = "On death, deal damage equal to Max HP X times to ALL enemies.",
      Link = "Corpse_Explosion",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_CorpseExplosion.png",
    },
    ["Choked"] = {
      Code = "$Choked",
      Text = "Whenever you play a card this turn, loses X HP.",
      Link = "Choke",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Choked.png",
    },
    ["Double Damage"] = {
      Code = "$Double Damage",
      Text = "{{QueryLink|Cards|type:Attack|Attacks}} deal double damage for X turns.",
      Link = "Phantasmal_Killer",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_DoubleDamage.png",
    },
    ["Energized (Silent)"] = {
      Code = "$EnergizedGE",
      Text = "Gain X additional @GE '''Energy''' next turn.",
      Link = "Buffs#Energized",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_EnergizedGreen.png",
    },
    ["Nightmare"] = {
      Code = "$Nightmare",
      Text = "Add X copies of the chosen card into your hand next turn.",
      Link = "Nightmare",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Nightmare.png",
    },
    ["Phantasmal"] = {
      Code = "$Phantasmal",
      Text = "Deal '''Double Damage''' for the next X turns.",
      Link = "Phantasmal_Killer",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_Phantasmal.png",
    },
    ["Poison"] = {
      Code = "$Poison",
      Text = "At the start of its turn, loses X HP, then reduce $Poison by 1.",
      Link = "Poison",
      Stacks = "Intensity and Duration",
      Type = "Debuff",
      Image = "Icon_Poison.png",
    },

    -- Silent Powers
    ["Accuracy"] = {
      Code = "$Accuracy",
      Text = "{{C|Shiv|Shivs}} deal X additional damage.",
      Link = "Accuracy",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Accuracy.png",
    },
    ["After Image"] = {
      Code = "$After Image",
      Text = "Whenever you play a card, gain X $Block.",
      Link = "After_Image",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_AfterImage.png",
    },
    ["Envenom"] = {
      Code = "$Envenom",
      Text = "Whenever you deal unblocked damage, apply X $Poison.",
      Link = "Envenom",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Envenom.png",
    },
    ["Infinite Blades"] = {
      Code = "$Infinite Blades",
      Text = "At the start of your turn, add X {{C|Shiv|Shivs}} to your hand.",
      Link = "Infinite_Blades",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_InfiniteBlades.png",
    },
    ["Noxious Fumes"] = {
      Code = "$Noxious Fumes",
      Text = "At the start of your turn, apply X $Poison to ALL enemies.",
      Link = "Noxious_Fumes",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_NoxiousFumes.png",
    },
    ["Retain Cards"] = {
      Code = "$Retain Cards",
      Text = "At the start of your turn, you may $Retain X cards.",
      Link = "Well-Laid_Plans",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Equilibrium.png",
    },
    ["Thousand Cuts"] = {
      Code = "$Thousand Cuts",
      Text = "Whenever you play a card, deal X damage to ALL enemies.",
      Link = "A_Thousand_Cuts",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_ThousandCuts.png",
    },
    ["Tools Of The Trade"] = {
      Code = "$Tools Of The Trade",
      Text = "At the start of your turn, draw X cards and discard X cards.",
      Link = "Tools_Of_The_Trade",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Tools.png",
    },
    ["Wraith Form"] = {
      Code = "$Wraith Form",
      Text = "At the start of your turn, lose X $Dexterity.",
      Link = "Wraith_Form",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_WraithForm.png",
    },

    -- Defect Effects
    ["Amplify"] = {
      Code = "$Amplify",
      Text = "Your next X {{QueryLink|Cards|type:Power|Power}} cards are played twice this turn.",
      Link = "Amplify",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_Amplify.png",
    },
    ["Energized (Defect)"] = {
      Code = "$EnergizedBE",
      Text = "Gain X additional @BE '''Energy''' next turn.",
      Link = "Charge_Battery",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_EnergizedBlue.png",
    },
    ["Equilibrium"] = {
      Code = "$Equilibrium",
      Text = "Retain your hand for X turns.",
      Link = "Equilibrium",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_Equilibrium.png",
    },
    ["Focus"] = {
      Code = "$Focus",
      Text = "Increases the effectiveness of Orbs by X.",
      Link = "Orbs#Focus",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Focus.png",
    },
    ["Lock-On"] = {
      Code = "$Lock On",
      Text = "Receives 50% more damage from Orbs for X turns.",
      Link = "Bullseye",
      Stacks = "Duration",
      Type = "Debuff",
      Image = "Icon_LockOn.png",
    },
    ["Rebound"] = {
      Code = "$Rebound",
      Text = "The next card you play this turn is put on top of your draw pile.",
      Link = "Rebound",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_Rebound.png",
    },

    -- Defect Powers
    ["Bias"] = {
      Code = "$Bias",
      Text = "At the start of your turn, lose X $Focus.",
      Link = "Biased_Cognition",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_Bias.png",
    },
    ["Creative AI"] = {
      Code = "$Creative AI",
      Text = "At the start of your turn, add X random {{QueryLink|Cards|type:Power|Power}} cards into your hand.",
      Link = "Creative_AI",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_CreativeAI.png",
    },
    ["Draw"] = {
      Code = "$Draw",
      Text = "At the start of your turn, draw X additional cards.",
      Link = "Machine_Learning",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_DrawCard.png",
    },
    ["Echo Form"] = {
      Code = "$Echo Form",
      Text = "The first X cards you play each turn are played twice.",
      Link = "Echo_Form",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_EchoForm.png",
    },
    ["Electro"] = {
      Code = "$Electro",
      Text = "$Lightning hits ALL enemies.",
      Link = "Electrodynamics",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Electro.png",
    },
    ["Heatsink"] = {
      Code = "$Heatsink",
      Text = "Whenever you play a {{QueryLink|Cards|type:Power|Power}} card, draw X cards.",
      Link = "Heatsinks",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Heatsink.png",
    },
    ["Hello"] = {
      Code = "$Hello",
      Text = "At the start of your turn, add X random {{QueryLink|Cards|rarity:Common|Common}} cards into your hand.",
      Link = "Hello_World",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Hello.png",
    },
    ["Loop"] = {
      Code = "$Loop",
      Text = "At the start of your turn, trigger the passive ability of your next Orb X times.",
      Link = "Loop",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Loop.png",
    },
    ["Static Discharge"] = {
      Code = "$Static Discharge",
      -- Ingame text does not tell damage must be unblocked
      Text = "Whenever you receive attack damage, $Channel X $Lightning.",
      Link = "Static_Discharge",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_StaticDischarge.png",
    },
    ["Storm"] = {
      Code = "$Storm",
      Text = "Whenever you play a {{QueryLink|Cards|type:Power|Power}} card, $Channel X $Lightning.",
      Link = "Storm",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Storm.png",
    },
    ["Repair"] = {
      Code = "$Repair",
      Text = "At the end of combat, heal X HP.",
      Link = "Self_Repair",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Repair.png",
    },

    -- Watcher Effects
    ["Blasphemer"] = {
      Code = "$Blasphemer",
      Text = "At the start of your turn, die.",
      Link = "Blasphemy",
      Stacks = "Does not stack",
      Type = "Debuff",
      Image = "Icon_Blasphemer.png",
    },
    ["Block Return"] = {
      Code = "$Block Return",
      Text = "When attacked, you gain X $Block.",
      Link = "Talk_To_The_Hand",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_BlockReturn.png",
    },
    ["Collect"] = {
      Code = "$Collect",
      Text = "At the start of your next X turns, put a {{C|Miracle|Miracle+}} into your hand.",
      Link = "Collect",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_EnergizedBlue.png",
    },
    ["Free Attack Power"] = {
      Code = "$Free Attack Power",
      Text = "Ignore energy cost on the next X {{QueryLink|Cards|type:Attack|Attacks}} you play.",
      Link = "Swivel",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_FreeAttackPower.png",
    },
    ["Mantra"] = {
      Code = "$Mantra",
      Text = "When you obtain 10 $Mantra, enter $Divinity.",
      Link = "Buffs#Mantra",
      Stacks = "Counter",
      Type = "Buff",
      Image = "Icon_Mantra.png",
    },
    ["Mark"] = {
      Code = "$Mark",
      Text = "Whenever you play {{C|Pressure Points}}, lose X HP.",
      Link = "Pressure_Points",
      Stacks = "Intensity",
      Type = "Debuffs",
      Image = "Icon_Mark.png",
    },
    ["Simmering Rage"] = {
      Code = "$Simmering Rage",
      -- Ingame text does not specify it lasts 1 turn.
      Text = "Enter $Wrath at the start of your turn.",
      Link = "Simmering_Fury",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Anger.png",
    },
    ["Wave of the Hand"] = {
      Code = "$Wave of the Hand",
      Text = "Whenever you gain $Block, apply X $Weak to ALL enemies.",
      Link = "Wave_of_the_Hand",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Wave.png",
    },

    -- Watcher Powers
    ["Battle Hymn"] = {
      Code = "$Battle Hymn",
      Text = "At the start of your turn, add X {{C|Smite|Smites}} into your hand.",
      Link = "Battle_Hymn",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_BattleHymn.png",
    },
    ["Deva"] = {
      Code = "$Deva",
      Text = "At the start of your turn, gain @PE X times and increase this gain by Y.",
      Link = "Deva_Form",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_DevaForm.png",
    },
    ["Devotion"] = {
      Code = "$Devotion",
      Text = "At the start of your turn, gain X $Mantra.",
      Link = "Devotion",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Devotion.png",
    },
    ["Establishment"] = {
      Code = "$Establishment",
      Text = "Whenever a card is $Retained, lower its cost by X.",
      Link = "Establishment",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Establishment.png",
    },
    ["Fasting"] = {
      Code = "$Fasting",
      Text = "At the start of your turn, lose X @PE '''Energy'''.",
      Link = "Fasting",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Fasting.png",
    },
    ["Foresight"] = {
      Code = "$Foresight",
      Text = "At the start of your turn, $Scry X.",
      Link = "Foresight",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Foresight.png",
    },
    ["Like Water"] = {
      Code = "$Like Water",
      Text = "At the end of your turn, if you are in $Calm, gain X $Block.",
      Link = "Like_Water",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_LikeWater.png",
    },
    ["Master Reality"] = {
      Code = "$MasterReality",
      Text = "Whenever a card is created, it is $Upgraded.",
      Link = "Master_Reality",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_MasterReality.png",
    },
    ["Mental Fortress"] = {
      Code = "$Mental Fortress",
      Text = "Whenever you switch $Stances, gain X $Block.",
      Link = "Mental_Fortress",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_MentalFortress.png",
    },
    ["Nirvana"] = {
      Code = "$Nirvana",
      Text = "Whenever you $Scry, gain X $Block.",
      Link = "Nirvana",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Nirvana.png",
    },
    ["Rushdown"] = {
      Code = "$Rushdown",
      Text = "Whenever you enter $Wrath, draw X cards.",
      Link = "Rushdown",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Rushdown.png",
    },
    ["Study"] = {
      Code = "$Study",
      Text = "At the end of your turn, shuffle X {{C|Insight|Insights}} into your draw pile.",
      Image = "Icon_Study.png",
      Stacks = "Intensity",
      Type = "Buff",
      Link = "Study",
    },
    ["Omega"] = {
      Code = "$Omega",
      Text = "At the end of your turn, deal X damage to ALL enemies.",
      Link = "Alpha",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Omega.png",
    },

    -- Colorless Effects
    ["No Block"] = {
      Code = "$No Block",
      -- Ingame text does not specify how long it lasts
      Text = "You cannot gain $Block from cards.",
      Link = "Panic_Button",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_NoBlock.png",
    },
    ["The Bomb"] = {
      Code = "$The Bomb",
      Text = "At the end of X turns, deal Y damage to ALL enemies.",
      Link = "The_Bomb",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Bomb.png",
    },
    -- used for the Pen Nib relic, wasn't sure where else to put this
    ["Pen Nib"] = {
    	Code = "$Pen Nib",
    	Text = "Your next {{QueryLink|Cards|type:Attack|Attack}} deals double damage.",
    	Link = "Pen_Nib",
    	Stacks = "Does not stack",
    	Type = "Buff",
    	Image = "Icon_PenNib.png"
    },

    -- Colorless Powers
    ["Magnetism"] = {
      Code = "$Magnetism",
      Text = "At the start of your turn, add X random {{QueryLink|Cards|color:Colorless|Colorless}} cards into your hand.",
      Link = "Magnetism",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Magnetism.png",
    },
    ["Mayhem"] = {
      Code = "$Mayhem",
      Text = "At the start of your turn, play the top X cards of your draw pile.",
      Link = "Mayhem",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Mayhem.png",
    },
    ["Panache"] = {
      Code = "$Panache",
      Text = "If you play X more cards this turn, deal Y damage to ALL enemies.",
      Link = "Panache",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Panache.png",
    },
    ["Sadistic"] = {
      Code = "$Sadistic",
      Text = "Whenever you apply a debuff to a enemy, deal X damage.",
      Link = "Sadistic_Nature",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Sadistic.png",
    },

    -- Enemy Effects
    ["Angry"] = {
      Code = "$Angry",
      Text = "Upon receiving attack damage, gains X $Strength.",
      Link = "Buffs#Angry",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Rage.png",
    },
    ["Beat of Death"] = {
      Code = "$Beat of Death",
      Text = "Whenever you play a card, take X damage.",
      Link = "Corrupt_Heart",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_BeatOfDeath.png",
    },
    ["Constricted"] = {
      Code = "$Constricted",
      Text = "Take X damage at the end of your turn.",
      Link = "Spire_Growth",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_Constricted.png",
    },
    ["Curiosity"] = {
      Code = "$Curiosity",
      Text = "Whenever you play a {{QueryLink|Cards|type:Power|Power}} card, gains X $Strength.",
      Link = "Awakened_One",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Curiosity.png",
    },
    ["Curl Up"] = {
      Code = "$Curl Up",
      Text = "Gains X $Block upon first receiving attack damage.",
      Link = "Louses",
      Stacks = "Intensity and Counter",
      Type = "Buff",
      Image = "Icon_CurlUp.png",
    },
    ["Draw Reduction"] = {
      Code = "$Draw Reduction",
      Text = "Draw X less cards next turn.",
      Link = "Time_Eater",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_DrawReduction.png",
    },
    ["Enrage"] = {
      Code = "$Enrage",
      Text = "Whenever you play a {{QueryLink|Cards|type:Skill|Skill}} card, gains X $Strength.",
      Link = "Gremlin_Nob",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Anger.png",
    },
    ["Entangled"] = {
      Code = "$Entangled",
      Text = "You may not play any {{QueryLink|Cards|type:Attack|Attacks}} this turn.",
      Link = "Red_Slaver",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_Entangled.png",
    },
    ["Explosive"] = {
      Code = "$Explosive",
      Text = "Explodes after X turns, dealing some amount of damage.",
      Link = "Shapes#Exploder",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_Explosive.png",
    },
    ["Fading"] = {
      Code = "$Fading",
      Text = "Dies in X turns.",
      Link = "Transient",
      Stacks = "Duration",
      Type = "Buff",
      Image = "Icon_Fading.png",
    },
    ["Flying"] = {
      Code = "$Flying",
      Text = "Takes 50% less attack damage. Cancelled if dealt attack damage X times in one turn. Resets charges at the start of next turn if not fully removed.",
      Link = "Byrd",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Flying.png",
    },
    ["Hex"] = {
      Code = "$Hex",
      Text = "Whenever you play a non-{{QueryLink|Cards|type:Attack|Attack}} card, shuffle X {{C|Dazed}} into your draw pile.",
      Link = "Chosen",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_Hex.png",
    },
    ["Invincible"] = {
      Code = "$Invincible",
      Text = "Can only lose X more HP this turn.",
      Link = "Corrupt_Heart",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Invincible.png",
    },
    ["Life Link"] = {
      Code = "$Life Link",
      Text = "If other {{M|Darkling|Darklings}} are still alive, revives in 2 turns.",
      Link = "Darkling",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_LifeLink.png",
    },
    ["Malleable"] = {
      Code = "$Malleable",
      Text = "Upon receiving attack damage, gains X $Block. $Block gain increases as $Malleable is triggered. Resets at the start of your turn.",
      Link = "Malleable",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Malleable.png",
    },
    ["Mode Shift"] = {
      Code = "$Mode Shift",
      Text = "After losing X HP, gains 20 $Block and changes current [[Intent]] to {{Int|The Guardian|Defensive Mode}}.",
      Link = "The Guardian",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_ModeShift.png",
    },
    ["Minion"] = {
      Code = "$Minion",
      Text = "Minions abandon combat without their leader.",
      Image = "Icon_Minion.png",
      Stacks = "Does not stack",
      Type = "Buff",
      Link = "Minions"
    },
    ["Painful Stabs"] = {
      Code = "$Painful Stabs",
      Text = "Whenever you receive attack damage from this enemy, add X {{C|Wound|Wounds}} into your discard pile.",
      Link = "Book_of_Stabbing",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_PainfulStabs.png",
    },
    ["Reactive"] = {
      Code = "$Reactive",
      Text = "Upon receiving attack damage, changes its [[Intent]].",
      Link = "Writhing_Mass",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Reactive.png",
    },
    ["Regenerate"] = {
      Code = "$Regenerate",
      Text = "At the end of its turn, heals X HP.",
      Link = "Awakened_One",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Regen.png",
    },
    ["Sharp Hide"] = {
      Code = "$Sharp Hide",
      Text = "Whenever you play an {{QueryLink|Cards|type:Attack|Attack}}, take X damage.",
      Link = "The Guardian",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_SharpHide.png",
    },
    ["Shifting"] = {
      Code = "$Shifting",
      Text = "Upon losing HP, loses that much $Strength until the end of the turn.",
      Link = "Transient",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Shifting.png",
    },
    ["Slow"] = {
      Code = "$Slow",
      Text = "Whenever you play a card, target receives 10% more damage from {{QueryLink|Cards|type:Attack|Attacks}} this turn. (Receives (X+10)% more damage)",
      Link = "Giant_Head",
      Stacks = "Intensity",
      Type = "Debuff",
      Image = "Icon_Slow.png",
    },
    ["Split"] = {
      Code = "$Split",
      Text = "When its HP is at or below 50%, it will split into 2 smaller Slimes with its current HP.",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Split.png",
    },
    ["Spore Cloud"] = {
      Code = "$Spore Cloud",
      Text = "On death, applies X $Vulnerable.",
      Link = "Buffs#Spore Cloud",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_SporeCloud.png",
    },
    ["Stasis"] = {
      Code = "$Stasis",
      Text = "On death, a stolen card is returned to your hand.",
      Link = "Bronze_Automaton",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Stasis.png",
    },
    ["Strength Up"] = {
      Code = "$Strength Up",
      Text = "At the end of its turn, gains $Strength.",
      Link = "Orb_Walker",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Stasis.png",
    },
    ["Surrounded"] = {
      Code = "$Surrounded",
      Text = "Receive 50% more damage if attacked from behind. Use targeting cards or potions to change your orientation.",
      Link = "Spire_Shield_and_Spire_Spear",
      Stacks = "Does not stack",
      Type = "Debuff",
      Image = "Icon_Surrounded.png",
    },
    ["Back Attack"] = {
      Code = "$Back Attack",
      Text = "Deals 50% more damage as it is attacking you from behind.",
      Link = "Spire_Shield_and_Spire_Spear",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Surrounded.png"
    },
    ["Thievery"] = {
      Code = "$Thievery",
      Text = "Steals X [[Gold]] whenever it attacks. Stolen gold is returned if this enemy is killed.",
      Link = "Thief",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_Thievery.png",
    },
    ["Time Warp"] = {
      Code = "$Time Warp",
      Text = "Whenever you play a certain number of cards, ends your turn and gains X $Strength.",
      Link = "Time_Eater",
      Stacks = "Intensity",
      Type = "Buff",
      Image = "Icon_TimeWarp.png",
    },
    ["Unawakened"] = {
      Code = "$Unawakened",
      Text = "This enemy hasn't awakened yet...",
      Link = "Awakened_One",
      Stacks = "Does not stack",
      Type = "Buff",
      Image = "Icon_Unawakened.png",
    },
}

local formatted = {}
for name, power in pairs(all_powers) do
	power.EditLink = "Module:Powers/data"
	formatted[name] = power
end

return formatted