// Generator for src/ui/icondata.ts — a pruned snapshot of ONLY the icons in
// USED_ICONS, so the runtime bundle doesn't carry the full @iconify-json sets
// (11k+ icons, ~10 MB of JSON). Run after changing USED_ICONS in
// src/ui/icons.ts:
//
//   bun tests/ui/gen-icondata.ts
//
// tests/ui/icons.test.ts asserts the snapshot is in sync with the real sets,
// so a stale or hand-edited snapshot fails CI. (Not a .test.ts file — bun
// test ignores it.)

import { icons as gameIcons } from "@iconify-json/game-icons";
import { icons as mdiIcons } from "@iconify-json/mdi";
import { getIconData } from "@iconify/utils";
import { USED_ICONS } from "../../src/ui/icons";

const out: Record<string, { body: string; width: number; height: number; left: number; top: number }> = {};
for (const name of USED_ICONS) {
  const sep = name.indexOf(":");
  const prefix = name.slice(0, sep);
  const iconName = name.slice(sep + 1);
  const set = prefix === "gi" ? gameIcons : prefix === "mdi" ? mdiIcons : null;
  if (!set) throw new Error(`unknown icon set prefix in ${name}`);
  const data = getIconData(set, iconName);
  if (!data) throw new Error(`icon not found: ${name}`);
  out[name] = {
    body: data.body,
    width: data.width ?? set.width ?? 16,
    height: data.height ?? set.height ?? 16,
    left: data.left ?? 0,
    top: data.top ?? 0,
  };
}

const file = `// GENERATED by tests/ui/gen-icondata.ts — do not edit by hand.
// Pruned Iconify data for exactly the icons in USED_ICONS (src/ui/icons.ts),
// keeping the full icon-set JSONs out of the runtime bundle.
// Regenerate after changing USED_ICONS:  bun tests/ui/gen-icondata.ts
//
// Sources & licenses:
//   game-icons.net via @iconify-json/game-icons — CC BY 3.0
//   Material Design Icons via @iconify-json/mdi — Apache License 2.0

export interface IconDatum {
  body: string;
  width: number;
  height: number;
  left: number;
  top: number;
}

export const ICON_DATA: Record<string, IconDatum> = ${JSON.stringify(out, null, 2)};
`;

await Bun.write(new URL("../../src/ui/icondata.ts", import.meta.url).pathname, file);
console.log(`wrote src/ui/icondata.ts with ${Object.keys(out).length} icons`);
