// Regenerates src/cli/render/heroPortraits.ts — the hero portrait tiers used
// by the menu — from the four character images:
//
//   bun tools/gen-hero-portraits.ts <dir-with-Ironclad.png,Silent.png,Defect.png,Watcher.png>
//
// Images are NOT checked into the repo; fetch them locally first, e.g. from
// https://slaythespire.wiki.gg/images/<Name>.png. Each hero is rendered at
// several widths (menu tiers) with the dark-terminal polarity (--invert).
// The 81-column Ironclad is Anthony's reference conversion, kept verbatim so
// regeneration is reproducible.

import { renderFile } from "./ascii-art";
import { join } from "node:path";

const OUT = join(import.meta.dir, "../src/cli/render/heroPortraits.ts");
const WIDTHS = [12, 16, 22, 30, 38, 46, 60, 81];
const HEROES: [string, string][] = [
  ["IRONCLAD", "Ironclad.png"],
  ["SILENT", "Silent.png"],
  ["DEFECT", "Defect.png"],
  ["WATCHER", "Watcher.png"],
];

/** Anthony's reference conversion of the Ironclad (81 cols). */
const IRONCLAD_81: string[] = [
  "                                                   ***",
  "                                               =-======+",
  "                                              +:====+++==",
  "                                              --++++++++++",
  "                                              =--=*++++++",
  "                                             *#%+==++##*",
  "                                          +=+++*%#%%#%%#++++*",
  " #                                      *+++++**%%%%%%#*+++++*#",
  "*==+*                               %** *+++**#%@%%#%%##*++++**",
  "**+++++=======++++++++++++++++++++++++***++***#######***#*****#",
  "  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%###***#%%%@%%##%%%%#*###%%",
  "                                         %**##%%%%%%%%%%%##*#%@",
  "                                             %#%%%%%%%@%@%##**#",
  "                                           @#%%%%%%%%%%@@%%###",
  "                                         #####%%%%%%%%%%#%",
  "                                         ###%%%%##*####%%%",
  "                                        %%%#####%%%%%%%%##%@",
  "                                       @%######%%%%%%%#####%%",
  "                                      %#%####%%%%%%%%%%%%###%%",
  "                                    %%######%%%%%%%%%%%%%%###%%",
  "                                    %#####%%%%@     @%%%%%%%%%#%",
  "                                  +*#%###%%%%          %%%%%%%%%",
  "                                  #+++***%%%             @%%%%%#**",
  "                                   *+++**##                @#++++*#",
  "                                    ****#                   **+**###",
  "                                    #**#                       %***##%",
  "                                    %**%                         %#*###",
  "                               @@@%##*##@@@@@@@@@@@@@@@@@@@@@@@@@@@###%@@",
  "          @@@@@@@@@@@@@@@@@@@@@@@%###%%@@@@@@@@@@@@@@@@@@@@@@@@@@@%###%@@@@@@@@",
  "                               @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%#%%@@@@@@@@@",
  "                                    @@@@@@@@@@@@@@            @@@@@@@@@@@",
];

const dir = process.argv[2];
if (!dir) {
  console.error("usage: bun tools/gen-hero-portraits.ts <dir-with-hero-pngs>");
  process.exit(1);
}

const tiers: Record<string, string[][]> = {};
for (const [id, file] of HEROES) {
  tiers[id] = [];
  for (const w of WIDTHS) {
    if (id === "IRONCLAD" && w === 81) {
      tiers[id]!.push(IRONCLAD_81);
      continue;
    }
    tiers[id]!.push(await renderFile(join(dir, file), w, true, 1.0));
  }
}

let src = `// GENERATED by tools/gen-hero-portraits.ts — do not edit by hand.
// Hero portrait tiers (ascending width) for the menu, rendered from the
// character images with tools/ascii-art.ts (dark-terminal polarity). The
// 81-column Ironclad is the checked-in reference conversion.
// Pure data: no imports, ASCII only.

export const HERO_PORTRAIT_ROWS: Record<string, string[][]> = {
`;
for (const [id] of HEROES) {
  src += `  ${id}: [\n`;
  for (const art of tiers[id]!) {
    src += "    [\n";
    for (const row of art) {
      src += `      ${JSON.stringify(row)},\n`;
    }
    src += "    ],\n";
  }
  src += "  ],\n";
}
src += "};\n";

await Bun.write(OUT, src);
console.log("wrote", OUT);
for (const [id] of HEROES) {
  console.log(id, tiers[id]!.map((a) => `${a.reduce((m, r) => Math.max(m, r.length), 0)}x${a.length}`).join("  "));
}
