// Regenerates src/cli/render/monsterPortraits.ts: an ASCII portrait of every
// monster, in five sizes, plus the tint each one wears.
//
//   bun tools/gen-monster-portraits.ts <dir-with-monster-pngs>
//
// Images are NOT checked into the repo. Fetch them locally first from
// https://slaythespire.wiki.gg/images/<File> using the MOB_IMAGES table below
// (those are the wiki's file names, which follow the game's internal names, so
// the Sneaky Gremlin is GremlinThief and the Mystic is Healer). Rendered with
// the dark-terminal polarity, same as the hero portraits.

import { loadImage, spriteTint, toAsciiArt } from "./ascii-art";
import { join } from "node:path";

const OUT = join(import.meta.dir, "../src/cli/render/monsterPortraits.ts");
// Each tier is the biggest aspect-correct render that fits inside a BOX, not a
// fixed width: sprites run from the Jaw Worm (twice as wide as tall) to the
// Bronze Orb (three times as tall as wide), so a fixed width would render the
// tall ones fifty rows deep and a fixed height would render the wide ones
// eighty columns across. Boxing every monster means each tier is usable in the
// same enemy column, whatever the creature's shape.
const BOXES: [number, number][] = [
  [12, 4],
  [18, 6],
  [26, 9],
  [34, 12],
  [46, 18],
];

const MOB_IMAGES: Record<string, string> = {
  CULTIST: "Cultist.png",
  JAW_WORM: "JawWorm.png",
  RED_LOUSE: "RedLouse.png",
  GREEN_LOUSE: "GreenLouse.png",
  ACID_SLIME_S: "AcidSlimeS.png",
  ACID_SLIME_M: "AcidSlimeM.png",
  ACID_SLIME_L: "AcidSlimeL.png",
  SPIKE_SLIME_S: "SpikeSlimeS.png",
  SPIKE_SLIME_M: "SpikeSlimeM.png",
  SPIKE_SLIME_L: "SpikeSlimeL.png",
  MAD_GREMLIN: "MadGremlin.png",
  SNEAKY_GREMLIN: "GremlinThief.png",
  FAT_GREMLIN: "GremlinFat.png",
  SHIELD_GREMLIN: "GremlinTsundere.png",
  GREMLIN_WIZARD: "GremlinWizard.png",
  LOOTER: "Looter.png",
  FUNGI_BEAST: "FungiBeast.png",
  BLUE_SLAVER: "SlaverBlue.png",
  RED_SLAVER: "SlaverRed.png",
  GREMLIN_NOB: "GremlinNob.png",
  LAGAVULIN: "Lagavulin.png",
  SENTRY: "Sentry.png",
  SLIME_BOSS: "SlimeBoss.png",
  THE_GUARDIAN: "TheGuardian.png",
  HEXAGHOST: "Hexaghost.png",
  SPHERIC_GUARDIAN: "SphericGuardian.png",
  CHOSEN: "Chosen.png",
  SHELLED_PARASITE: "ShelledParasite.png",
  BYRD: "Byrd.png",
  MUGGER: "Mugger.png",
  CENTURION: "Centurion.png",
  MYSTIC: "Healer.png",
  SNAKE_PLANT: "SnakePlant.png",
  SNECKO: "Snecko.png",
  BOOK_OF_STABBING: "BookOfStabbing.png",
  GREMLIN_LEADER: "GremlinLeader.png",
  TASKMASTER: "Taskmaster.png",
  BRONZE_AUTOMATON: "BronzeAutomaton.png",
  BRONZE_ORB: "BronzeOrb.png",
  THE_COLLECTOR: "TheCollector.png",
  TORCH_HEAD: "TorchHead.png",
  THE_CHAMP: "Champ.png",
  BEAR: "Bear.png",
  ROMEO: "Romeo.png",
  POINTY: "Pointy.png",
  DARKLING: "Darkling.png",
  ORB_WALKER: "OrbWalker.png",
  SPIKER: "Spiker.png",
  REPULSOR: "Repulsor.png",
  EXPLODER: "Exploder.png",
  TRANSIENT: "Transient.png",
  THE_MAW: "Maw.png",
  SPIRE_GROWTH: "SpireGrowth.png",
  WRITHING_MASS: "WrithingMass.png",
  GIANT_HEAD: "GiantHead.png",
  NEMESIS: "Nemesis.png",
  REPTOMANCER: "Reptomancer.png",
  DAGGER: "Dagger.png",
  AWAKENED_ONE: "AwakenedOne.png",
  TIME_EATER: "TimeEater.png",
  DONU: "Donu.png",
  DECA: "Deca.png",
  SPIRE_SHIELD: "SpireShield.png",
  SPIRE_SPEAR: "SpireSpear.png",
  CORRUPT_HEART: "CorruptHeart.png",
};

const dir = process.argv[2];
if (!dir) {
  console.error("usage: bun tools/gen-monster-portraits.ts <dir-with-monster-pngs>");
  process.exit(1);
}

const ids = Object.keys(MOB_IMAGES).sort();
const tiers: Record<string, string[][]> = {};
const tints: Record<string, string> = {};
for (const id of ids) {
  const img = await loadImage(join(dir, `${id}.png`));
  tints[id] = spriteTint(img);
  // terminal cells are twice as tall as wide: rendering w columns costs
  // w * imgH / (2 * imgW) rows, so take whichever bound the box hits first
  tiers[id] = BOXES.map(([boxW, boxH]) => {
    const rowsAtBoxW = (boxW * img.h) / (2 * img.w);
    const w = rowsAtBoxW <= boxH ? boxW : Math.round((2 * boxH * img.w) / img.h);
    return toAsciiArt(img, Math.max(3, w), true, 1.0);
  });
}

let src = `// GENERATED by tools/gen-monster-portraits.ts - do not edit by hand.
// Every monster as ASCII, in five sizes (ascending), plus the tint taken
// from its sprite so each creature keeps its own color. Rendered from the
// character images with tools/ascii-art.ts (dark-terminal polarity).
// Pure data: no imports, ASCII only.

export const MONSTER_PORTRAIT_ROWS: Record<string, string[][]> = {
`;
for (const id of ids) {
  src += `  ${id}: [\n`;
  for (const art of tiers[id]!) {
    src += "    [\n";
    for (const row of art) src += `      ${JSON.stringify(row)},\n`;
    src += "    ],\n";
  }
  src += "  ],\n";
}
src += "};\n\nexport const MONSTER_TINTS: Record<string, string> = {\n";
for (const id of ids) src += `  ${id}: ${JSON.stringify(tints[id])},\n`;
src += "};\n";

await Bun.write(OUT, src);
console.log("wrote", OUT);
for (const id of ids) {
  const dims = tiers[id]!.map((a) => `${a.reduce((m, r) => Math.max(m, r.length), 0)}x${a.length}`).join(" ");
  console.log(`${id.padEnd(18)} ${tints[id]}  ${dims}`);
}
